### ISSUE TITLE
Distribute binary with nix

### ISSUE THREAD

**Issue by nikitavoloboev** [yqrashawn/GokuRakuJoudo#1]
I can try write a nix expression for it.

If Goku uses nix we [can automate it](https://github.com/webnf/lein-nix).

**Comment by yqrashawn** [comment]
What does this `lein-nix` tool do, seems it's not finished.
We just need nix to download the executable and put it in PATH.

**Comment by nikitavoloboev** [comment]
> What does this lein-nix tool do

It should generate a nix expression from lein. This way you can install Goku with nix easily.

I'll try put goku binary in `/usr/local/bin` manually I suppose. Where did you put yours?

**Comment by yqrashawn** [comment]
I have ~/.local/bin in PATH.

Note that goku needs graalvm to compile it in to native executable. The compile procedure takes 5G RAM on my machine and maybe 5 minutes. So we shouldn't do the compile stuff on user's machine. Since this only needs to work on macos.

**Comment by nikitavoloboev** [comment]
@yqrashawn I [added goku to nixpkgs](https://github.com/NixOS/nixpkgs/pull/49273). Now you can install it with Nix.

I will add a service to [nix-darwin](https://github.com/LnL7/nix-darwin) soon too so this can be closed.
