### ISSUE TITLE
How to make shift work with simulateous key presses 

### ISSUE THREAD

**Issue by tintinthong** [yqrashawn/GokuRakuJoudo#101]
Im a big fan of simulatenous key presses but would love it they worked using modifier with goku configuraiton.

```
[[:j :k] :equal_sign]
[:!S[:j :k] :!Sequal_sign] ;; obviously doesn't work
```

**Comment by yqrashawn** [comment]
related to this https://github.com/yqrashawn/GokuRakuJoudo/issues/72#issuecomment-669022383

**Comment by tintinthong** [comment]
@yqrashawn does simultaneous key presses also work if you "hold it" to enter a layer?

**Comment by yqrashawn** [comment]
[**@tintinthong**](https://github.com/tintinthong) commented on [Jan 6, 2021, 11:37 PM GMT+8](https://github.com/yqrashawn/GokuRakuJoudo/issues/101#issuecomment-755371835 "2021-01-06T15:37:01Z - Replied by Github Reply Comments"):
> @yqrashawn does simultaneous key presses also work if you "hold it" to enter a layer?

Can you explain it a bit further?

Say, `sj` and `sk` both enters layer `s` then insert `a` and `b`.

`s down j down j up k down k up` do insert `ab`.

Don't know if this what you are asking.

**Comment by yqrashawn** [comment]
This is supported now.

Try this:
```clojure
[{:sim [:j :k] :modi [:left_shift]} :!Sequal_sign]
```
