### ISSUE TITLE
How do I get the proper vendor id and product id from mac?

### ISSUE THREAD

**Issue by tintinthong** [yqrashawn/GokuRakuJoudo#106]
Basiclaly, I get addresses 

For example, running `system_profiler SPUSBDataType` gives me a product id 0x31c and vndor id 0x046d. But I want to get the numbers instead. What is the product id and vendor id in number form?

**Comment by yqrashawn** [comment]
![image](https://user-images.githubusercontent.com/15090582/104000849-ccc2be80-51d9-11eb-8291-40a7437d0f62.png)
You can check it in `Karabiner-EventViewer.app`.
