### ISSUE TITLE
Recreate all modifiers and arrows on home row keys?

### ISSUE THREAD

**Issue by chrismo** [yqrashawn/GokuRakuJoudo#107]
As I've played around with this, I think what I had conceived of is just a bit too nuts for either Karabiner-Elements or goku. The basic idea is to have the left hand home row keys replace shift, option, and command, and the right hand home row keys be arrow keys. 

I tried a couple approaches with layers and simlayers, and while just holding the `f` key to go into "command+arrows" worked well and was simple (j,k,i,l being the arrows), adding in the `s` key for shift is what got me. I tried even just doing it straight in karabiner.json, and came up with one approach that was better than what I could get with goku, but still not adequate.

Anyway - I'm still a n00b and it's totally fine if this is out of scope for what these tools can do, but I've also seen some fairly fancy stuff, so I figured it couldn't hurt to ask.

**Comment by yqrashawn** [comment]
> I tried even just doing it straight in karabiner.json, and came up with one approach that was better than what I could get with goku, but still not adequate.

Can you share your config in json format here?

**Comment by chrismo** [comment]
Actually, I kept picking away at this and came up with this .edn. It's only the left arrow, and only option / shift, but so far is working. :) 

```edn
{:profiles {:Default {:default true
                      ;; simultaneous_threshold_milliseconds (def: 50)
                      ;; keys need to be pressed within this threshold to be considered simultaneous
                      :sim     50
                      ;; to_delayed_action_delay_milliseconds (def: 500)
                      ;; basically it means time after which the key press is count delayed
                      :delay   500
                      ;; to_if_alone_timeout_milliseconds (def: 1000)
                      ;; hold for 995s and single tap registered; hold for 1005s and seen as modifier
                      :alone   1000
                      ;; to_if_held_down_threshold_milliseconds (def: 500)
                      ;; key is fired twice when 500 ms is elapsed (otherwise seen as a hold command)
                      ;; increase this value to allow you to hold a simlayer key longer before the next key is pressed
                      :held    1000}}
 :main     [;
             {:des   "from j to opt+shift+left if opt-shift-arrow-mode"
              :rules [[:j :!SOleft_arrow :opt-shift-arrow-mode]]};
             {:des   "from sim [f,s,j] to opt+shift+left and set opt-shift-arrow-mode until after key_up"
              :rules [[{:sim  [:f :s :j]
                        :simo {:interrupt true
                               :dorder    :insensitive
                               :uorder    :insensitive
                               :afterup   {:set ["opt-shift-arrow-mode" 0]}}}
                       [{:set ["opt-shift-arrow-mode" 1]} :!SOleft_arrow]
                       nil
                       {:params {:sim 250}}]]}
             {:des   "from sim [s,j] to opt+shift+left and set opt-shift-arrow-mode until after key_up and unset opt-arrow _all_ if opt-arrow set"
              :rules [:opt-arrow-mode
                      [{:sim  [:s :j]
                        :simo {:interrupt true
                               :dorder    :insensitive
                               :uorder    :insensitive
                               :afterup   [{:set ["opt-shift-arrow-mode" 0]}
                                           {:set ["opt-arrow-mode" 1]}]}}
                       [{:set ["opt-shift-arrow-mode" 1]}
                        {:set ["opt-arrow-mode" 0]}
                        :!SOleft_arrow]
                       nil
                       {:params {:sim 250}}]]}
             {:des   "from s to opt-shift-arrow-mode if opt-arrow-mode"
              :rules [:opt-arrow-mode
                      [:s
                       ["opt-shift-arrow-mode" 1]
                       nil
                       {:afterup [["opt-shift-arrow-mode" 0] ["opt-arrow-mode" 1]]}]]}
             {:des   "from j to opt+left if opt-arrow-mode"
              :rules [:opt-arrow-mode
                      [:j :!Oleft_arrow]]}
             {:des   "from sim [f,j] to opt+left and set opt-arrow-mode until after key_up"
              :rules [[{:sim  [:f :j]
                        :simo {:interrupt true
                               :dorder    :insensitive
                               :uorder    :insensitive
                               :afterup   {:set ["opt-arrow-mode" 0]}}}
                       [{:set ["opt-arrow-mode" 1]} :!Oleft_arrow]
                       nil
                       {:params {:sim 250}}]]}
             ;
             ]
 ;
 }

```

**Comment by chrismo** [comment]
```edn
:rules [[{:sim  [:f :s :j]
                        :simo {:interrupt true
                               :dorder    :insensitive
                               :uorder    :insensitive
                               :afterup   {:set ["opt-shift-arrow-mode" 0]}}}
                       [{:set ["opt-shift-arrow-mode" 1]} :!SOleft_arrow]
                       nil
                       {:params {:sim 250}}]]}
```

this rule is used 3 times so far with very little variation. is there a way to DRY this out?

**Comment by chrismo** [comment]
bah, there's a use case here that doesn't work, overlapping simultaneous rules and inconsistent afterup behavior - but it's a karabiner issue, not goku. even if that wasn't a problem, there are too many accidental triggers this way during normal typing anyway. 

if there are any useful goku tips to do anything that I've done simpler, I'd still like to learn better goku syntax, but ... on the primary issue I'm going to have to take a different approach.

**Comment by yqrashawn** [comment]
Here is an example using goku's [simlayer](https://github.com/yqrashawn/GokuRakuJoudo/blob/master/tutorial.md#simlayers).
2 + hjkl... to enter k2-mode and trigger corresponding keys when it's not in tab-mode or tmux-winmove-mode 
[code1](https://github.com/yqrashawn/yqdotfiles/blob/b45c4ced0206ebd8a1b34a40291f8ca1a35aeb94/.config/karabiner.edn#L45) [code2](https://github.com/yqrashawn/yqdotfiles/blob/b45c4ced0206ebd8a1b34a40291f8ca1a35aeb94/.config/karabiner.edn#L85)

**Comment by chrismo** [comment]
The second links are using just layer, not simlayer, which I'd read wasn't a good option if I type quickly?

**Comment by chrismo** [comment]
This is much simpler - toggle caps-key into the mode, then I can just do everything straightforward.

```edn
{:profiles {:Default {:default true
                      ;; simultaneous_threshold_milliseconds (def: 50)
                      ;; keys need to be pressed within this threshold to be considered simultaneous
                      :sim     50
                      ;; to_delayed_action_delay_milliseconds (def: 500)
                      ;; basically it means time after which the key press is count delayed
                      :delay   500
                      ;; to_if_alone_timeout_milliseconds (def: 1000)
                      ;; hold for 995s and single tap registered; hold for 1005s and seen as modifier
                      :alone   1000
                      ;; to_if_held_down_threshold_milliseconds (def: 500)
                      ;; key is fired twice when 500 ms is elapsed (otherwise seen as a hold command)
                      ;; increase this value to allow you to hold a simlayer key longer before the next key is pressed
                      :held    1000}}

 :main     [;
             {:des   "escape kills all home row modifier arrow modes"
              :rules [[:escape
                       [:escape
                        {:set ["arrows-mode" 0]}
                        {:set ["shift-mode" 0]}
                        {:set ["command-mode" 0]}
                        {:set ["option-mode" 0]}]]]}

             {:des   "toggle arrows with caps"
              :rules [[:caps_lock ["arrows-mode" 0] :arrows-mode]
                      [:caps_lock ["arrows-mode" 1]]]}

             {:des   "modifiers"
              :rules [:arrows-mode
                      [:s ["shift-mode" 1] nil {:afterup ["shift-mode" 0]}]
                      [:d ["command-mode" 1] nil {:afterup ["command-mode" 0]}]
                      [:f ["option-mode" 1] nil {:afterup ["option-mode" 0]}]]}

             {:des   "arrows plain"
              :rules [[:condi :arrows-mode :!shift-mode :!command-mode :!option-mode]
                      [:j :left_arrow]
                      [:k :down_arrow]
                      [:l :right_arrow]
                      [:i :up_arrow]]}

             {:des   "arrows shift"
              :rules [[:condi :arrows-mode :shift-mode :!command-mode :!option-mode]
                      [:j :!Sleft_arrow]
                      [:k :!Sdown_arrow]
                      [:l :!Sright_arrow]
                      [:i :!Sup_arrow]]}

             {:des   "arrows command"
              :rules [[:condi :arrows-mode :!shift-mode :command-mode :!option-mode]
                      [:j :!Cleft_arrow]
                      [:k :!Cdown_arrow]
                      [:l :!Cright_arrow]
                      [:i :!Cup_arrow]]}

             {:des   "arrows option"
              :rules [[:condi :arrows-mode :!shift-mode :!command-mode :option-mode]
                      [:j :!Oleft_arrow]
                      [:k :!Odown_arrow]
                      [:l :!Oright_arrow]
                      [:i :!Oup_arrow]]}

             {:des   "arrows shift-command"
              :rules [[:condi :arrows-mode :shift-mode :command-mode :!option-mode]
                      [:j :!SCleft_arrow]
                      [:k :!SCdown_arrow]
                      [:l :!SCright_arrow]
                      [:i :!SCup_arrow]]}

             {:des   "arrows shift-option"
              :rules [[:condi :arrows-mode :shift-mode :!command-mode :option-mode]
                      [:j :!SOleft_arrow]
                      [:k :!SOdown_arrow]
                      [:l :!SOright_arrow]
                      [:i :!SOup_arrow]]}
             ;
             ]
 ;
 }
```

**Comment by kiinoda** [comment]
@chrismo i wonder if this does what you actually want? it's a snippet from my config.

```clojure
        {
            :des "Extend Layer - CapsLock (quick release for ESC)"
            :rules [
                [:##caps_lock ["extend" 1] [:!symbols :!mouse :!shifted :!system] {:afterup ["extend" 0] :alone :escape}]
                :extend
                    ; functions
                    [:##1 :f1][:##2 :f2][:##3 :f3][:##4 :f4][:##5 :f5][:##6 :f6]
                    [:##7 :f7][:##8 :f8][:##9 :f9][:##0 :f10][:##hyphen :f11][:##equal_sign :f12]
                    ; modifiers
                    [:##a :left_control][:##s :left_shift][:##d :left_option][:##f :left_command]
                    ; arrows
                    [:##j :left_arrow]
                    [:##k :down_arrow]
                    [:##i :up_arrow]
                    [:##l :right_arrow]
                    ; shortcuts
                    [:##u :!Cleft_arrow :!terminals]
                    [:##o :!Cright_arrow :!terminals]
                    [:##z :!Cz][:##x :!Cx][:##c :!Cc][:##v :!Cv]
            ]
        }
```

**Comment by chrismo** [comment]
Wow! I totally didn't understand what `##` actually did. I thought I knew, but ... that's perfect :) I have a long-hand version of this tracking my own variables to send things like `:!SCleft_arrow` that's so much simpler now. I'd be facepalming if I wasn't so happy. Thx again!

**Comment by Rougemoot** [comment]
I'm not sure I understand everything I see here, but it might be in the right area for what I want to do:

Is there any way I can have home row mods in karabiner using the `simultaneous` feature? It's my understanding that just remapping a key with `if_alone` won't work because if I type too fast I'll get many false positives (because karabiner doesn't have something like IGNORE_MOD_TAP_INTERRUPT in QMK), but that something like that is achievable with `simultaneous`.

Another headscratcher is that I'd want to have home row mods (at least shift on A and ;), while keeping some of my combos, for example the one I have on `AS`.

**Comment by igoragoli** [comment]
@Vermoot, [here](https://github.com/Erlendms/karabiner-actions/blob/main/README.md)'s an example of how to use `simultaneous` to achieve home row mods.

I've just copied one of their rules and used it on top of my Goku config, but please let me know if you ended up writing home row mods in the Goku format 🙂

**Comment by eugenesvk** [comment]
In the general way, home row mods are impossible in Karabiner, it doesn't support the necessary conditions and also there is no scripting to track them

The best you can do is have a mandatory delay before F becomes Shift (or your other mod layer trigger), but then any typing will work (so `function` will not bug), though you'd also need to bind all F+a-u-z combinations to type these pairs to achieve that

**Comment by farzadmf** [comment]
@eugenesvk thank you for your reply

> have a mandatory delay before F becomes Shift (or your other mod layer trigger)

Can you please give me some pointers how to achieve this?

> you'd also need to bind all F+a-u-z combinations to type these pairs

Could you please elaborate a bit?

---

Also, it might be worth for me to add this:
I _am_ thinking of ultimately buying a QMK keyboard, and I recently learned that you can achieve these home row modifications with Karabiner as well (I don't want the to be modifiers like SHIFT, CTRL, etc. but I want them to "activate a layer")

And I'm very much against getting used to something specific (software, hardware, etc.) so that you'd only have to use that for the rest of your life (quite the opposite of Apple's ideology I'd say).

So, I'm basically trying to mimic what I'll have in the future using a "real" keyboard.

Althought I must definitely say that I don't know how the QMK layer activation works; I thought what I mentioned above (holding something for a time to activate a layer and remain there until that key is released) is how they'd work

**Comment by eugenesvk** [comment]
If you're starting from stratch it might be worth checking out https://github.com/jtroo/kanata app instead, its x-platform and doesn't require a QMK keyboard and is meant to be a full-featured replacement, so it has proper home row mod support unlike Karabiner

>  I thought what I mentioned above (holding something for a time to activate a layer and remain there until that key is released) is how they'd work

This not a good implementation as it has a mandatory delay, but it's one of the ways it could work. QMK (at least some fork modifications of it) have a better method that doesn't always require a delay

> Can you please give me some pointers how to achieve this?

Here is a part of my goku config for home row mods https://gist.github.com/eugenesvk/8fdfef3bb1552b68aafcf8cf2fca6853, it should be ok to illustrate the logic, but can't be used as is since I'm using an unmerged fork with various syntax improvements

For example, this defines <kbd>F</kbd> as a home row mod by setting an `mF` variable just like you've described (**but** only with a mandatory **delay**)
```edn
  [:f nil [:!mJ :!mK :!mL :!m︔                   ;mF
                        :!m' :!sim_v :!mB :!t⸴ :!m‹⇧ :!m⇧› :!multitouch_extension_finger_count_upper_half_area] ;:!m␠
   {:alone {:key :f :halt true} :delayed{:canceled[:f]} :held{:set["mF"1] :repeat false} :afterup{:set["mF"0]}
    :params{:alone 164 :held 165 :delay 165} }]
```

and this defines `mF` variable to emit Capitalized letters (or type a pair for same-side letters)
```edn
 {:des "  [⌂⇧] 🠿F⃣ to ‹Shift: 🠿F⃣ ⟶ ‹⇧" :rules [ :mF
  ; ←Left half types ⇧Key (also mod key isn't swallowed)
  [:⎋ :‹⇧⎋] [:f1 :‹⇧f1] [:f2 :‹⇧f2] [:f3 :‹⇧f3] [:f4 :‹⇧f4] [:f5 :‹⇧f5]
  [:non_us_backslash :‹⇧non_us_backslash] [:⭾ :‹⇧⭾]
  [:1 :‹⇧1] [:2 :‹⇧2] [:3 :‹⇧3] [:4 :‹⇧4] [:5 :‹⇧5]
  ; disable same-side modifier (no swallow) activation for alpha keys
  [:q [:f :q]] [:w [:f :w]] [:e [:f :e]] [:r [:f :r]] [:t [:f :t]]
  [:a [:f :a]] [:s [:f :s]] [:d [:f :d]] [:f [:f :f]] [:g [:f :g]]
  [:z [:f :z]] [:x [:f :x]] [:c [:f :c]] [:v [:f :v]] [:b [:f :b]]
  ; disable same-side modifier (   swallow) activation for alpha keys
  ;[:q :‹⇧q] [:w :‹⇧w] [:e :‹⇧e] [:r :‹⇧r] [:t :‹⇧t]
  ;[:a :‹⇧a] [:s :‹⇧s] [:d :‹⇧d] [:f :‹⇧f] [:g :‹⇧g]
  ;[:z :‹⇧z] [:x :‹⇧x] [:c :‹⇧c] [:v :‹⇧v] [:b :‹⇧b]
  ; →Right half types ⇧Key (also mod key isn't swallowed)
  [:f6 :‹⇧f6] [:f7 :‹⇧f7] [:f8 :‹⇧f8] [:f9 :‹⇧f9] [:f10 :‹⇧f10] [:f11 :‹⇧f11] [:f12 :‹⇧f12]
  [:6 :‹⇧6] [:7 :‹⇧7] [:8 :‹⇧8] [:9 :‹⇧9] [:0 :‹⇧0] [:hyphen :‹⇧hyphen] [:₌ :‹⇧₌]
  [:y :‹⇧y] [:u :‹⇧u] [:i :‹⇧i] [:o :‹⇧o] [:p :‹⇧p] [:open_bracket :‹⇧open_bracket] [:close_bracket :‹⇧close_bracket]
  [:h :‹⇧h] [:j :‹⇧j] [:k :‹⇧k] [:l :‹⇧l] [:︔ :‹⇧︔] [:quote :‹⇧quote] [:backslash :‹⇧backslash]
  [:n :‹⇧n] [:m :‹⇧m] [:⸴ :‹⇧⸴] [:． :‹⇧．] [:⁄ :‹⇧⁄]
  [:∀﹖delete_or_backspace :‹⇧␈] [:∀﹖return_or_enter :‹⇧⏎]
  [:∀﹖◀ :‹⇧◀] [:∀﹖▶ :‹⇧▶] [:∀﹖▲ :‹⇧▲] [:∀﹖▼ :‹⇧▼]
  ]}
```

But you can change the second part to be a much simpler cursor movement or whatever (and if you only have a single layer you also don't need all the exclusions/exceptions/combinations that are present in the file, so would be much simpler)

> you'd also need to bind all F+a-u-z combinations to type these pairs

> Could you please elaborate a bit?

I got confused a bit, with a delay you don't need to do this for regular fast typing

**Comment by farzadmf** [comment]
> If you're starting from stratch it might be worth checking out https://github.com/jtroo/kanata app instead

Oh no @eugenesvk what did you do? You gave me _at least_ one week worth of research and reading 😆 

Joke aside, thank you for the detailed answer. I didn't know about `kanata`; looks really interesting. I'm _not_ starting from scratch, but I'm willing to redo things if it's worth it.

> I got confused a bit, with a delay you don't need to do this for regular fast typing, it will work as usual since no home row mods will be triggered

By elaborating, I meant basically _how_ to add a delay, but I guess that's done in your config sample. I'll check that out as well.

**Comment by farzadmf** [comment]
@eugenesvk looking at `kanata`, I was wondering if it's possible to have app-specific bindings /mappings (similar to `karabiner`)

Tried to search for it there, but didn't find anything. I'm guessing it's an os-specific things, so it might not be implemented in `kanata`.

Apparently, using `karabiner` and `kanata` together is not an option either, since it seems like each need exclusive access to the "driver".

**Comment by eugenesvk** [comment]
You've correctly identified two biggest issues with kanata, so unfortunately it can't be a full replacement to Karabiner.

Ideally if you could use them together, you could then use kanata to have fully functional home row mods and Karabiner for all the other app-specific stuff

The per-app bindings are os-specific, there is an external solution/"exension" for Win/Linux, but not sure there is one for a Mac

**Comment by farzadmf** [comment]
Thank you @eugenesvk ; that's what I thought

> there is an external solution/"exension" for Win/Linux

Do you have a link or something for those?

Also, question: seems like every time I [re]start `kanata`, I get that "keyboard setup" dialog (the one prompting to press the keys located right/left of the left/right shift keys). Do you know if there's a way to avoid that?

And also, since `kanata` isn't in `brew` to have a service or something, do you have a way (or a link) on how to start it at log in?

**Comment by eugenesvk** [comment]
app extensions are listed on the front page https://github.com/jtroo/kanata#community-projects-related-to-kanata

not sure about the rest as I haven't yet switched to kanata on a Mac
