### ISSUE TITLE
How to map all keys in layers to null? 

### ISSUE THREAD

**Issue by tintinthong** [yqrashawn/GokuRakuJoudo#112]
Hi, I want to know two things:

- how to map a single key to null (thought it was using the keyword :nil but its not)
- or disable all keys that are not specified within a layer ( I guess id have to protect some layer shifting keys - this actually sounds bit dangerous )

Thanks in advance.

**Comment by yqrashawn** [comment]
try `:vk_none`

**Comment by Barbabosco** [comment]
Thank you @yqrashawn! Really useful!

**Comment by SmashMineGame** [comment]
where do I need to add `:vk_none`?

**Comment by yqrashawn** [comment]
> where do I need to add `:vk_none`?

You can use it in the <to> section.

**Comment by SmashMineGame** [comment]
When I add `:vk_none` to the rules section, all of my rules stop working. Is there an example I can look at somewhere?
