### ISSUE TITLE
Simultaneous keys with optional modifiers

### ISSUE THREAD

**Issue by Rougemoot** [yqrashawn/GokuRakuJoudo#114]
H!

I've just started using Goku to make my karabiner config, and what a difference it's made!

One thing I like, as a frenchman, is to map accented letters on combos, so in karabiner-speak, simultaneous events. For example, I do `ER` to type `é`.

Here's what it looks like in my `karabiner.edn` file:

```clojure
           :des "Combo accents"
           :rules [
             [[:e :r] [:quote :e]]
```

What I'd like to be able to do is use those with optional modifiers, especially shift, to be able to type capitalised accented letters. Here's what I thought it would look like:

```clojure
           :des "Combo accents"
           :rules [
             [[:##e :##r] [:quote :##e]]
```

Unfortunately, this doesn't work. What's the right way of doing this? Thanks

**Comment by yqrashawn** [comment]
I missed this feature when implementing goku. I'll find time to add it. Related issue https://github.com/yqrashawn/GokuRakuJoudo/issues/72#issuecomment-669022383

**Comment by tintinthong** [comment]
@yqrashawn r u open for me to make a pr on this? if so, can you give me some high-level steps, otherwise, ill just figure it out.

**Comment by yqrashawn** [comment]
Hi, this is fixed now.

For rule **simultaneously** press **any modifier** + e and **same any modifier + r** ----to----> insert **same any modifier + quote** then insert **same any modifier + e** can be done like below

```clojure
[{:sim [:e :r] :modi {:optional [:any] }} [:quote :e]]
```

simultaneously press **option + e** and **option + r** ----to----> insert quote then insert **option + e**

```clojure
[{:sim [:e :r] :modi {:mandatory [:left_option]}} [:quote :!Oe]]
```
For deatils about modifiers in from, you can checkout karabiner's documentation https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/from/modifiers/#frommodifiersmandatory
