### ISSUE TITLE
Pointing Button with Modifier causes error

### ISSUE THREAD

**Issue by MunifTanjim** [yqrashawn/GokuRakuJoudo#115]
This EDN

```edn
  {:des "Ctrl+Left Click => Cmd+Left Click (select multiple items)"
   :rules [[:!Tbutton1 :!Cbutton1]]}
```

generates JSON:

```json
      {
        "description" : "Ctrl+Left Click => Cmd+Left Click (select multiple items)",
        "manipulators" : [ {
          "from" : {
            "key_code" : "button1",
            "modifiers" : {
              "mandatory" : [ "left_control" ]
            }
          },
          "to" : [ {
            "key_code" : "button1",
            "modifiers" : [ "left_command" ]
          } ],
          "type" : "basic"
        } ]
      }
```

It causes this error:

![image](https://user-images.githubusercontent.com/8050659/106502220-4a829d00-64ee-11eb-85e5-ae3a88959998.png)

It should be `pointing_button` instead of `key_code`

**Comment by yqrashawn** [comment]
It should be `[{:pkey :button1 :modi :left_control} {:pkey :button1 :modi :left_command}]`.

The doc is in the code. Seems we should put it in the tutorial.
https://github.com/yqrashawn/GokuRakuJoudo/blob/05847304bcd3c6fdb4e62652bb81acd88a76700d/src/karabiner_configurator/froms.clj#L18

**Comment by farzadmf** [comment]
Hey,

I'm using this rule, but it doesn't seem to change anything (ctrl-click still behaves as it was before):
```
{
  :main [
    { :des "ctrl-click -> cmd-click?"
      :rules [
        [{:pkey :button1 :modi :left_control} {:pkey :button1 :modi :left_command}]
      ]
    }
  ]
}
```

I'm guessing this rule should do with the `:des` is saying, right? Do I need to configure something else for this to work? 🤔

Thank you

**Comment by farzadmf** [comment]
Great, thank you @MuhammedZakir , that took care of one issue

But another issue I have is that the combination of `ctrl` from built-in keyword + touchpad click doesn't seem to be picked up

When I hold `ctrl` on my external/internal keyboard and click with external mouse, the behavior is as intended, but for some reason, the touchpad click doesn't seem to care 🙁, and it's still doing the old ctrl-click

**Comment by MuhammedZakir** [comment]
I don't know about external trackpad, but you can't modify events from built-in trackpad. There seems to be some issues when trying to do that, so it's disabled / not implemented.
