### ISSUE TITLE
GOKU_EDN_CONFIG_FILE path not found

### ISSUE THREAD

**Issue by SilasWegg1** [yqrashawn/GokuRakuJoudo#118]
Hi,

I'm trying to use goku but having copied your example .edn file to the .config directory and setting GOKU_EDN_CONFIG_FILE to the correct path using the command goku I get the message:-

Syntax error in config:
Error:  open :/Users/jonathanclark/.config/karabiner/example.edn: no such file or directory

using echo gives me

Jonathans-iMac% echo $GOKU_EDN_CONFIG_FILE
:/Users/jonathanclark/.config/karabiner/example.edn

I downloaded goku today (07/02/2021) and I am using MAC X 10.13.6 and using Karabiner 12.10.0

I would be very grateful if you could suggest what I might be doing wrong or if there are any issues concerning this

Thank You

Regards

Jonathan (SilasWegg1)

**Comment by yqrashawn** [comment]
I can't reproduce this on my machine. Can you make sure there's `example.edn` exists in `~/.config/karabiner/`?

![image](https://user-images.githubusercontent.com/15090582/108693634-03118e80-7539-11eb-9bb0-bf0cdbf69cf5.png)
