### ISSUE TITLE
Can I only activate the trackpad based on a sim-layer?

### ISSUE THREAD

**Issue by atanasj** [yqrashawn/GokuRakuJoudo#119]
I use an external keyboard and trackpad on my MBP and would like the external trackpad to be in a similar position to when I use the MPB without the external peripherals. However, I always bump the external trackpad when typing.

Is there a way to only activate the external trackpad (or internal one for that matter) when I hold a particular key down e.g., "q"?

**Comment by atanasj** [comment]
This doesn't seem to be a feature in karabiner at the moment, so hopefully this will be available via `goku` when/if it gets implemented in [`karabiner-elements`](https://github.com/pqrs-org/Karabiner-Elements/issues/2628).

Will leave open as a placeholder but feel free to close if this is the right course of action.

**Comment by yqrashawn** [comment]
This should be done in karabiner. Goku can only change the karabiner.json on disk. 
It's too slow to write to the disk and wait for karabiner to detect the changed file on disk for this scenario.

Also goku only supports change the `complex_modifications` field for each profile for now.

![image](https://user-images.githubusercontent.com/15090582/108692549-b6798380-7537-11eb-9c2a-629c4f687571.png)

If karabiner do support this some day and there's something to do with `complex_modifications`, goku will add support for it. Feel free to reopen this issue by then.
