### ISSUE TITLE
How to batch keystrokes together

### ISSUE THREAD

**Issue by nikitavoloboev** [yqrashawn/GokuRakuJoudo#12]
It's not clear how I can batch multiple keystrokes together in the action.

I want to make a binding on b key to insert `TODO: `. With a space after.

I would think I'd have to do something like this `[:b [:T][:O]]` to achieve this but not sure. The tutorial is not clear about it either.

**Comment by yqrashawn** [comment]
it's `[:b [:!St :!So :!Sd :!So]]`.

**Comment by nikitavoloboev** [comment]
thanks
