### ISSUE TITLE
`select_input_source` is not working 

### ISSUE THREAD

**Issue by wd** [yqrashawn/GokuRakuJoudo#125]
Config snippets, I want to map right_shift to escape and change the input source id to ABC when it presses alone.
The mapping for escape is working, but the input source won't change.

```
    :tos {
        :input_cn
            {:key :escape
             :select_input_source {
                 :input_source_id "com.apple.keylayout.ABC"
             }}
        }

    :main [
        {
            :des "right_shift(alone) -> Esc",
            :rules [
                [:right_shift :right_shift nil {:alone :input_cn}]
            ]
        },
       ..........
      ]
```

**Comment by yqrashawn** [comment]
You can use shortcusts for inputs.

First specify the input like this https://github.com/yqrashawn/yqdotfiles/blob/3cf0621f9c498807030ca5f56738655d09484b59/.config/karabiner.edn#L634
Then use it with the `:input` keyword in `:tos` or `:rules` like this https://github.com/yqrashawn/yqdotfiles/blob/3cf0621f9c498807030ca5f56738655d09484b59/.config/karabiner.edn#L14

I also added support for raw `:select_input_source` in `:tos` in 0.3.11.

**Comment by wd** [comment]
Thanks, get it working
```
    :input-sources {
        :abc {:input_source_id "^com\\.apple\\.keylayout\\.ABC$"}
    }
    :tos {
        :select_abc [{:input :abc}
                     {:key :escape}]
        }
    :main [
        {
            :des "right_shift(alone) -> Esc",
            :rules [
                [:right_shift :right_shift nil {:alone :select_abc}]
            ]
        },
```
