### ISSUE TITLE
JSON for Mouse button 5 + Right Click to Left Click?

### ISSUE THREAD

**Issue by Dexterity420** [yqrashawn/GokuRakuJoudo#126]
Tried all night trying to write something for this, haven't gotten anywhere!

`{
                        "description": "Mouse 5 + Right Click to Left Click",
                        "manipulators": [
                            {
                                "from": {
                                    "pointing_button": "button5",
                                    "pointing_button": "button2"
                                },
                                "to": [
                                    {
                                        "pointing_button": "button1"
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    },`

**Comment by yqrashawn** [comment]
Hi, simultaneous pointing buttons is supported in 0.3.11 now.

Try this
```clojure
{:des "Mouse 5 + Right Click to Left Click"
 :rules [[[{:pkey :button5} {:pkey :button2}] {:pkey :button1}] ]}
```
