### ISSUE TITLE
Delay between sending keys? possible?

### ISSUE THREAD

**Issue by Madd0g** [yqrashawn/GokuRakuJoudo#128]
I have this sequence of keys pressed:

```edn
[:!COreturn_or_enter [:!Ca :left_arrow :return_or_enter :up_arrow]]
```

any way to tell karabiner to wait between `:left_arrow` and `:return_or_enter`?

**Comment by yqrashawn** [comment]
Basically, there are two options
1. use the delayed action (only able to delay once, check link below)
2. use applescript

related issues:
https://github.com/yqrashawn/GokuRakuJoudo/issues/75
https://github.com/yqrashawn/GokuRakuJoudo/issues/148#issuecomment-963789553
