### ISSUE TITLE
images?

### ISSUE THREAD

**Issue by rowe-morehouse** [yqrashawn/GokuRakuJoudo#129]
really glad I found Goku — thanks!!

how did you make the images for the readme? … what tool?

this: 

![image](https://user-images.githubusercontent.com/2647082/116778522-3a178b00-aa27-11eb-931f-9c3b0c73f2ba.png)

**Comment by nikitavoloboev** [comment]
Probable this: https://carbon.now.sh

**Comment by yqrashawn** [comment]
Yes, i'm not for sure but i think it's carbon.now.sh
