### ISSUE TITLE
Conditions in afterup, possible?

### ISSUE THREAD

**Issue by Madd0g** [yqrashawn/GokuRakuJoudo#134]
I'm trying to set a variable in `:held` and then do something in `:afterup` only if the variable is set.

Is that somehow possible?

**Comment by yqrashawn** [comment]
According to [karabiner's doc](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to-after-key-up/), it's not possible to define conditions in `:afterup` since `to_after_up` is just a to event defination. You may need to find other way to implement this.
