### ISSUE TITLE
How do I write the colon ":" Character?

### ISSUE THREAD

**Issue by SmashMineGame** [yqrashawn/GokuRakuJoudo#136]
I'm trying to write some rules for VIM involving the `:` (colon) character. I've tried `:key` but that isn't working for me. I'm trying to create shortcuts to type `:w` and `:q` and then press the return key.

**Comment by yqrashawn** [comment]
It's shift + semicolon `:Ssemicolon`.
You can find all keys [here](https://github.com/yqrashawn/GokuRakuJoudo/blob/master/src/karabiner_configurator/keys_info.clj#L64)
