### ISSUE TITLE
feature request: custom path for joker and  watchexec 

### ISSUE THREAD

**Issue by tami5** [yqrashawn/GokuRakuJoudo#139]
Hi there, is there away to add a custom path to joker and  watchexec  binary, I use nix and nix stores binaries in wired places.

It would be great to be able to define the paths using env variables
Thanks

**Comment by lATAl** [comment]
I also have the same problem

**Comment by tami5** [comment]
Thanks @yqrashawn, will  watchexec work as side effect?

**Comment by yqrashawn** [comment]
Actually watchexec is used in to places.
1. the gokuw file, which is just a sh file https://github.com/yqrashawn/GokuRakuJoudo/blob/0d8030c680edac85c603f6d8e4a7bdc9ed1e03f7/.github/workflows/build-and-release.yaml#L37
2. the homebrew service file https://github.com/yqrashawn/homebrew-goku/blob/133932221f1740d1fb7a9ff39a6ae28728f70b29/Formula/goku.rb#L30

If you are not using homebrew, there won't be the second plist file.
You can just need to run the gokuw file with watchexec in PATH
