### ISSUE TITLE
:froms aliases don't work in :layers

### ISSUE THREAD

**Issue by NeighNeighNeigh** [yqrashawn/GokuRakuJoudo#142]
Currently it seems we are unable to use :froms in :layers. For example, this works:
```
:layers    {
     :modal1 {:key :k}
}
```
Where this does not:
```
:froms {
     :myfrom {:key :k}
}
:layers    {
     :modal1 :myfrom
}
```
It would be very helpful if these aliases could be used here.

**Comment by yqrashawn** [comment]
That's the supposed way. All predefined things only works in `:main` section.
