### ISSUE TITLE
caps_lock to control and to escape when alone is not working

### ISSUE THREAD

**Issue by maindoor** [yqrashawn/GokuRakuJoudo#143]
Hi Team,

I have a simple config like so: 
       {
        :des   "caps_lock to esc when pressed alone, to ctrl as modifier"
        :rules [[:##caps_lock :left_control nil {:alone :escape}]]
       }

1) whenever I single-tap caps_lock, it sends left_control down/up followed by  escape down/up.
2) when I hold down caps_lock it sends left_control. 
Some how my Macbook 2019 i-9 isn't recognizing the escape sequence being sent to it.
eg. bring-up spot light search, single-tap caps_lock, nothing happens. event viewer confirmed 1) above.
even in Vi when I go to insert mode, single-tap caps_lock does not go to normal mode. even viewer confirmed 1) above.
Note: This exact same config works on 2015 Macbook pro. :( . Both are on Big Sur!

What could be wrong ?

Thanks.

**Comment by ooloth** [comment]
@maindoor I'm having the issue you describe as (1) above.

Do you remember what third-party tool was interfering?

**Comment by maindoor** [comment]
Keyboard maestro was interfering
