### ISSUE TITLE
Activating Application Switcher With Mouse

### ISSUE THREAD

**Issue by lukakemperle** [yqrashawn/GokuRakuJoudo#144]
I would like to activate mac' native application switcher with my Naga Pro mouse (macro key). 

Pressing `⌘  tab` works, but rather than releasing both simultaneously, I would keep pressing the `⌘` key in order to keep the switcher displayed on the screen (and selecting the app with my mouse). Selecting the app would cancel the switcher and `⌘` (long) press.

```
{:des "f-mode"
  :rules [ :f-sim
	  [:a :!Ctab]
]}
``` 
Thank you for your help!

**Comment by yqrashawn** [comment]
I don't think it's possible.

the native app switcher is

1. confirm on release command
2. deactivate on release command

so you must release something to make it disappear

karabiner can't define things like press and release as far as I know.

you can use app switcher from BetterTouchTool/Keyboard Maestro, or something like Context.app to active this

**Comment by lukakemperle** [comment]
> you can use app switcher from BetterTouchTool/Keyboard Maestro, or something like Context.app to active this

Yes, you're right: KM or BTT would be better and more customizable. 
-Thanks for the suggestion.
