### ISSUE TITLE
How can I run shell and then type keys

### ISSUE THREAD

**Issue by fjchen7** [yqrashawn/GokuRakuJoudo#148]
Here is my configuration
```edn
:templates {
  :open "open \"%s\""
}
{:des "launch"
  :rules [
    [:!Og [:open "/Applications/Alfred 4.app" :g :spacebar]}]
  ]
}
```
I want to open `Alfred` and then type `g` and `spacebar` in sequence. My configuration above doesn't work. How can I do it?

**Comment by yqrashawn** [comment]
karabiner won't execute each action synchronously, you need to use applescript to implement this.
There're tons of examples on stackoverflow for 
1. running shell script with applescript
2. pressing keys with applescript
3. add delay between actions in applescript
