### ISSUE TITLE
Bootstrap failed eror

### ISSUE THREAD

**Issue by drsnn** [yqrashawn/GokuRakuJoudo#155]
xHi,  I have get error when I run ```brew services start goku``` in M1 mac.

 ```Bootstrap failed: 5: Input/output error
Try re-running the command as root for richer errors.
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Users/username/Library/LaunchAgents/homebrew.mxcl.goku.plist` exited with 5.```


Could you help me ?  Thanks

**Comment by drsnn** [comment]
Hi again,  i can run ```brew services start goku``` command but after  when I run ```goku``` or ```gokuw``` command I get ```ERROR: Can't find profile named "goku" in karabiner.json, please create a profile named "goku" using the Karabiner-Elements.app.
Failed!``` error. I have  karabiner.edn in config file and also  karabiner.json with default profile.   Thanks for help.

**Comment by yqrashawn** [comment]
You need to open the karabiner GUI and create or rename a profile to Goku

**Comment by yqrashawn** [comment]
I installed goku on a fresh Mac the other day without that error. 

Can you share your solution about the launchctl error if it's solved?

**Comment by drsnn** [comment]
Hi again, Thank you very much after I created goku profile, it is working now. Thanks. 

For launchctl error, I used  [stackoverflow](https://stackoverflow.com/a/69578416/6838539). I restart goku not start. ```brew services restart goku```. Thank you very much again. Happy new years.

**Comment by yqrashawn** [comment]
Thanks for your sharing. Happy new year.
