### ISSUE TITLE
Setting repeat to false with multiple "to" keys in the "other options" section?

### ISSUE THREAD

**Issue by dannylittle715** [yqrashawn/GokuRakuJoudo#156]
I'm trying to get the functionality of: if comma is pressed once, it is a comma, but if held down, it becomes an exclamation point. Here's what the rule looks like:
```
[:comma :comma nil {:held [:delete_or_backspace :!S1]}]
```
This gets me what I want, but if I hold comma for a little too long then the exclamation point repeats. I know you can do:
```
[:comma :comma nil {:held {:key :!S1 :repeat false}}]
```
But, this does not work- the backspace is needed to delete the comma. Is there a way to set repeat to false in a block like this?

**Comment by yqrashawn** [comment]
try set `:held` to `[{:key :delete_or_backspace :repeat false} {:key :!S1 :repeat false}]`
it should work
the definition of each `to` can be found [here](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to/)
and goku parse it like [this](https://github.com/yqrashawn/GokuRakuJoudo/blob/1985026225e18d5078cec32553e72cb462794db4/src/karabiner_configurator/tos.clj#L7)
