### ISSUE TITLE
Add support for `to.software_function`

### ISSUE THREAD

**Issue by ofalvai** [yqrashawn/GokuRakuJoudo#159]
Karabiner now supports a native way to sleep the system (instead of the AppleScript workaround): https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to/software_function/iokit_power_management_sleep_system/

It would be great to use this syntax in Goku with other `software_function`s.

**Comment by yqrashawn** [comment]
Thanks for the issue, software_function support is added in 0.7.0

config example can be found at https://github.com/yqrashawn/GokuRakuJoudo/commit/8dfe510eeaec58c3314afceab0e4b8ac20cfa4ba#diff-bdf007c27f040fdb32781729c690e316b78cb697fac1e9b4f14f19aeb0cff70fR92-R691

**Comment by farzadmf** [comment]
Oh great to see this; thank you @yqrashawn for this; I was so sad thinking that the project might be abandoned since I love this project and how it helps me be sane when configuring Karabiner!

**Comment by yqrashawn** [comment]
Thanks, it's just the current code base is ugly, I have a refactor plan using [malli](https://github.com/metosin/malli?tab=readme-ov-file#coercion) in my mind, and it takes time so it never happens
