### ISSUE TITLE
Converting from json?

### ISSUE THREAD

**Issue by Madd0g** [yqrashawn/GokuRakuJoudo#16]
I found (and made) a bunch of json configurations. Then I found Goku.
If Goku uses its own profile, can I somehow combine its json output with existing json modifications?
Or maybe there's a way to convert json rules into goku rules?

I tried searching for all this but I couldn't find people having this problem.
Any advice? I want to use for example the Mouse Keys modification from the website, but the json is over 900 lines, how should I go about converting it or using it in conjunction with new rules that I'd write in Goku?

Thanks

**Comment by Madd0g** [comment]
So it took like 4 hours, but I managed to copy all my most used rules to the goku syntax. I'm pretty happy because editing the json was seriously depressing.

Can you please help me with the things I couldn't figure out on my own?

1. I have right_option mapped to cmd+tab when pressed alone with the following snippet:

```edn 
{:des "right option -> previous program" :rules [[:right_option :right_option nil {:alone :!Ctab}]]}
```

but when I add my external keyboard mappings (using vendor ids) that flip the command and the option keys, it either maps to the wrong key (command instead of option) or doesn't work at all, depending on which rule is first in the file, any hints for this?

2. I'm trying to press enter when 'e' is held, but press regular 'e' when it's tapped, I just can't get it to work, this is what I tried and it produces an 'e' when I'm holding the key. I have many key holding rules I haven't done because I can't figure out this one.

```edn
{:des "long e -> enter" :rules [[:e {:key :e :repeat false} nil {:held :return_or_enter}]]}
```

3. How to set the timeout for a `delayed` action? I have this and it's resetting too quickly, I want the variable to stay alive for 500ms

```edn 
{:des "double cmd"
         :rules [
            [:right_command [:spacebar ["rcmd_pressed" 0]] ["rcmd_pressed" 1]]
            [:right_command :right_command nil {:delayed {:invoked ["rcmd_pressed" 0] :canceled ["rcmd_pressed" 0]} :alone ["rcmd_pressed" 1]}]
        ]}
```

4. I copied from your dotfile the double cmd+q handling, `!C#Pq` - what does the P stand for? I couldn't find it in the docs.

5. In the old karabiner I used multi-key sequences, don't even know how to call it, using `KEYTOKEY_DELAYED_ACTION` which allows to assign not just simple <char>+K or <char>+B but also <char>+K+K. I'm guessing it's possible? With multiple variables or something?

Thanks!

**Comment by yqrashawn** [comment]
{:des "hold keys" :rules [
    [:open_bracket nil nil { :alone :open_bracket :held {:key :!S9 :repeat false :halt true }}, { :alone 50 :held 50 }]
    [:close_bracket nil nil { :alone :close_bracket :held {:key :!S0 :repeat false :halt true }}, { :alone 50 :held 50 }]
]}

**Comment by Madd0g** [comment]
2  
Yay, I put the :params in the wrong place initially, but after I looked closer and moved one curly brace, holding is finally almost perfect! Thank you so much, I'm so happy to have all my brackets on the same key finally.

Now the only problem left with holding is letters, because letters are usually typed fast and no matter which number I put in `:alone` it swallows the letter, this is what I tried:

```edn
[:e nil nil { :alone :e :held {:key :return_or_enter :repeat false :halt true } :params { :held 200 :alone 50 }}]
```

I'm trying to remap 'e' to enter when held. But with this rule, when I type 'power' it comes out as 'powr' unless I wait a while aftr hitting th lettr 'e'.

I opened [this issue](https://github.com/tekezo/Karabiner-Elements/issues/1667) in KE, do you think it's a bug or just a matter of plugging in the right number?

**Comment by yqrashawn** [comment]
By the way, why you are setting helding e to enter. Held is way more slow than just press entre imho.

**Comment by Madd0g** [comment]
>By the way, why you are setting helding e to enter. Held is way more slow than just press entre imho.

I don't use it while typing, more while navigating webpages, when I only use my left hand I can do quite a lot from my left side of the keyboard, besides pressing enter, for which I do not have a good mapping on the left side. Enter is needed when I have something focused after a search or after tabbing between fields for example and I don't want reach with my right hand.

I'm going to think of a nice simultaneous pair I think, maybe `[:e :f]`
