### ISSUE TITLE
Question about (multiple) conditions

### ISSUE THREAD

**Issue by farzadmf** [yqrashawn/GokuRakuJoudo#161]
Hi, I'm following the tutorial, but using multiple conditions doesn't seem to work for me: 

So, I start with this one:
```edn
{:applications {:chrome ["^com\\.google\\.Chrome$"]}
 :main [{:des "a to 1 chrome" :rules [[:a :1 :chrome]]}]}
```
and this, as expected, changes `a` to `1` only in Chrome

But then I change it to this:
```edn
{:applications {:chrome ["^com\\.google\\.Chrome$"]
                :safari ["^com\\.apple\\.Safari$"]}
  :main [{:des "a to 1 only in chrome, safari" :rules [[:a :1 [:chrome :safari]]]}]}
```

and `a` keeps being `a` no matter what window I'm in.

Can you please tell me what I'm missing here?

**Comment by lukakemperle** [comment]
+1

**Comment by Dimentium** [comment]
you can try to use the aggregated application rule:
```
{
:applications {
               :browsers ["^com\\.google\\.Chrome$"
                          "^com\\.apple\\.Safari$"]
               }
:main [
       {:des "a to 1 only in chrome, safari" 
        :rules [
                [:a :1 :browsers]
               ]
       }
      ]
}
```

**Comment by yqrashawn** [comment]
`[:chrome :safari]` means “when application is chrome **AND** safari”. Please try @Dimentium's snippet.

**Comment by farzadmf** [comment]
Hey @yqrashawn , sorry for the late reply.

Unfortunately, I didn't get a chance to try this, but what I included in the issue is I think a copy paste of [the tutorial](https://github.com/yqrashawn/GokuRakuJoudo/blob/master/tutorial.md#tap-a-to-insert-1-only-in-google-chrome), where it's using `[:chrome :safari]`

So, does that mean the tutorial is wrong?

Also, would it be possible to have a list of supported "keywords"? For example, Karabiner's JSON has `description`, but this tool seems to use `des` for that
