### ISSUE TITLE
How to set Dvorak

### ISSUE THREAD

**Issue by baldore** [yqrashawn/GokuRakuJoudo#173]
Hello!

First at all, thanks for such an amazing application. I want to move to Dvorak, but when I set the Keyboard Layout to Dvorak, some keys act weird. Not sure what's going on, or if I need to do something directly on Karabiner. Any help is welcome. 

Thanks in advance.

**Comment by Dimentium** [comment]
> Hello!
> 
> First at all, thanks for such an amazing application. I want to move to Dvorak, but when I set the Keyboard Layout to Dvorak, some keys act weird. Not sure what's going on, or if I need to do something directly on Karabiner. Any help is welcome.
> 
> Thanks in advance.

hi!
can you use Karabiner-EventViewer to see what's going on?

**Comment by sidharthv96** [comment]
I'm using Karabiner directly for Colemak-DH, so you could try the same for Dvorak.

https://github.com/sidharthv96/dotfiles/blob/3f0be11937a9dc7a66170df7e817e16cf8fd3880/.config/karabiner.edn#L128-L148
