### ISSUE TITLE
After upgraded to 0.5.5, "Error: Invalid profiles"

### ISSUE THREAD

**Issue by kimitrois** [yqrashawn/GokuRakuJoudo#181]
Hi author,
I am a no techy person. So I can only describe what happened.
Before the upgrading ,everything works fine, I type the command "goku" and it replies "done!"
But after I have upgraded to version 0.5.5, it failed to work. With no changes in my karabiner.edn , I typed gokuw and it returns 
"➜  ~ gokuw                                 
ERROR: Invalid profiles. Must be a map
Failed!
[[Command exited with 1]]  "

----
I don't know if it is a bug ...but could you pls tell me how to fix this? 
And thanks for your effort which enables me to use karabiner with ease!

**Comment by Falco-Technology** [comment]
I am experiencing the same error when using both commands `goku` & `gokuw` after upgrading to **0.5.5**

Also might be noteworthy that the command `goku -V` shows the version as **0.5.3** when running **0.5.5**

**Comment by yqrashawn** [comment]
Fixed in v0.5.6
