### ISSUE TITLE
Set multiple variables

### ISSUE THREAD

**Issue by eugenesvk** [yqrashawn/GokuRakuJoudo#197]
Is it possible to set multiple variables in the `other options`?
```
#↓ this works
:held [{:set ["varA" 1] :repeat false} {:set ["varB" 1] :repeat false}] 
```

**Comment by sokinpui** [comment]
try this instead:
`:held [{:set [["varA" 1] ["varB" 1]] :repeat false}`

**Comment by eugenesvk** [comment]
Doesn't work, it considers the first box as a name and the second as a value
