### ISSUE TITLE
[ BUG ] (macOS Ventura) Can't run the service; Calling plist_options is deprecated

### ISSUE THREAD

**Issue by ibehnam** [yqrashawn/GokuRakuJoudo#210]
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/58621210/218291237-c5525676-0e23-487b-b8d9-4bddc3287fae.png">

**Comment by aLucaz** [comment]
same error, @ibehnam can you tell me if you found a workaround?

**Comment by aLucaz** [comment]
<img width="1377" alt="image" src="https://user-images.githubusercontent.com/38844194/225912866-d39f817f-fceb-4288-937d-fb954fd4856b.png">

**Comment by davidscotson** [comment]
Lots of other brew installs seem to hit the same issue, one example where they've replaced the plist with a service setup is here, but there's probably a few to look at for examples:

https://github.com/koekeishiya/homebrew-formulae/pull/30/files

**Comment by yqrashawn** [comment]
Fixed now, run `brew reinstall yqrashawn/goku/goku` to fix the homebrew service.

> > same error, @ibehnam can you tell me if you found a workaround?
> 
> Unfortunately no :/ I ended up removing Goku. Shame, because its syntax was much shorter than Karabiner's JSON.
> 
> I also believe in reproducibility of my workflow, so I'll most likely never use Goku again even if this specific problem is fixed. Imagine setting up your machine and then 5 years later, having to do it all over again because one piece of software stopped working.

@ibehnam  Sorry to hear that. I feel your frustration. I recommend strongly you to use nix instead of homebrew since you care about reproducibility and this issue is caused by homebrew in the first place.

@davidscotson Thanks for your helpful comments.

**Comment by ibehnam** [comment]
@yqrashawn Thanks for explaining. I appreciate all the work put into Goku. I reinstalled it and it went well. Although the Gokuw command doesn't work.
