### ISSUE TITLE
Makefile.local build fails vs makefile

### ISSUE THREAD

**Issue by eugenesvk** [yqrashawn/GokuRakuJoudo#215]
The extra options `-J-Dclojure.compiler.elide-meta=[:doc :file :line :added]`, specifically `:line :added` are unknown 
```
/Library/Java/JavaVirtualMachines/openjdk19-graalvm/Contents/Home/bin/native-image -H:+ReportUnsupportedElementsAtRuntime --no-server -J-Dclojure.compiler.elide-meta=[:doc :file :line :added] -J-Dclojure.spec.skip-macros=true -Djdk.internal.lambda.eagerlyInitialize=false -jar target/karabiner-configurator-0.1.0-standalone.jar
Warning: Ignoring server-mode native-image argument --no-server.
Error: Unknown arguments: :line, :added]
make[2]: *** [bin] Error 1
```

Removing those leads to 
```
Failed generating ':file]' after 11.5s.
```

Removing that one proceeds with initialization fine, but then breaks 
```
Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing com.fasterxml.jackson.core.JsonFactory.<clinit>()
Parsing context: <no parsing context available>
```
Removing the whole `-J-Dclojure.compiler.elide-meta` didn't help

Tweaking the regular makefile to the same `native-image` path builds fine

Or adding `--initialize-at-build-time` seems to do the trick
Not sure what the proper substitute for the removed options is and what the last flag does, but would be nice is the template/instructions were updated to whatever is correct

**Comment by yqrashawn** [comment]
Thanks for the issue
make local is removed
`make all` works fine as long as there's `native-image` in `PATH`
