### ISSUE TITLE
Typo in tutorial "Command a to Control 1" example: missing ":rules" and "[]"

### ISSUE THREAD

**Issue by jfhector** [yqrashawn/GokuRakuJoudo#219]
Hello!

Thanks for a great tool and helpful docs and examples.

[On the tutorial page, the "Command a to Control 1" example](https://github.com/yqrashawn/GokuRakuJoudo/blob/master/tutorial.md#command-a-to-control-1) currently reads like this:
```md
{:main [{:des "command a to control 1" [:!Ca :!T1]}]}
```

That doesn't compile.
It needs to be corrected to:
```md
{:main [{:des "command a to control 1" :rules [[:!Ca :!T1]]}]}
```

Note the addition of:
- :rules
- []

**Comment by karimelhajoui63** [comment]
Hi, 

there is the same for:

```
{:des "g to 4 when variable vi-mode is 1" :rules [:j :4 :vi-mode]} ;; vi-mode is 1
```

This should be: 

```
{:des "g to 4 when variable vi-mode is 1" :rules [[:j :4 :vi-mode]]} ;; vi-mode is 1
```


 (There is others like this in the exemple file)
