### ISSUE TITLE
Using an optional parameter in a template?

### ISSUE THREAD

**Issue by Madd0g** [yqrashawn/GokuRakuJoudo#22]
I'm not familiar with clojure, is there a way to make the third parameter optional?

```java
:templates {
  :alfred "osascript -e 'tell application \"Alfred 3\" to run trigger \"%s\" in workflow \"%s\" with argument \"%s\"'"
}
```

I added the third `%s` and now I'm getting errors because I have many callers without the 3rd argument, is there a way to mark it as optional?

Thanks

**Comment by yqrashawn** [comment]
I'll look into it to see if there's any work arounds.

https://github.com/yqrashawn/GokuRakuJoudo/blob/master/src/karabiner_configurator/tos.clj#L79

**Comment by nikitavoloboev** [comment]
I had a similar issue where and I solved it by making another template that does take a third argument.

https://github.com/nikitavoloboev/dotfiles/blob/master/karabiner/karabiner.edn#L1

**Comment by Madd0g** [comment]
@nikitavoloboev - thanks for the suggestion!

**Comment by yqrashawn** [comment]
Added in v0.2.1.
