### ISSUE TITLE
zsh: bad CPU type in executable: goku

### ISSUE THREAD

**Issue by suliveevil** [yqrashawn/GokuRakuJoudo#222]
<img width="316" alt="image" src="https://user-images.githubusercontent.com/35763237/235279379-1fc35c58-f9d7-4919-9c82-b8fd405c98d2.png">

Never encounter this bug before on the same device in the last two years.

Is there a way to make goku work? Thank you very much.

**Comment by grancalavera** [comment]
@suliveevil try this https://apple.stackexchange.com/questions/408375/zsh-bad-cpu-type-in-executable

**Comment by yqrashawn** [comment]
There's `goku-arm.zip` in recent releases, just download the zip, unzip and replace your `goku` with the unzipped one
