### ISSUE TITLE
Using Goku without Homebrew

### ISSUE THREAD

**Issue by oonis** [yqrashawn/GokuRakuJoudo#23]
I noticed that there is a nix package for Goku, but I can't figure out how to actually use it without using a brew service. Would be nice to have some manual or Nixpkgs documentation.

**Comment by nikitavoloboev** [comment]
> how to actually use it without using a brew service

It was something I wanted to add but didn't have enough Nix skills for that.

The service can be ran/started with [nix-darwin](https://github.com/LnL7/nix-darwin) and I also need to update Goku package on nixpkgs.

**Comment by oonis** [comment]
Oh I see! Sorry for the late response, but I figured it was something that had to be done manually.
