### ISSUE TITLE
Yabai - function with arguments

### ISSUE THREAD

**Issue by lukakemperle** [yqrashawn/GokuRakuJoudo#232]
Hi there,
I would like to execute a function (yabai) with the argument living outside the `karabiner.edn`:

karabiner.edn:
```
{:des "b-mode" :rules [ :b-sim
  [:p "~/.config/yabai/actions grid"]
]}
```

~/.config/yabai/*actions.sh*:
```
function float() {
  yabai -m window --toggle float
}

function grid() {
  yabai -m window --grid 3:1:1:1:1:1
}

if [ "$1" == "float" ] ; then
  float
elif [ "$1" == "grid" ] ; then
  grid
fi

# /usr/local/bin/yabai
```

Could please someone enlighten me on what I'm doing wrong - executing file in the terminal *with arguments* works (eg. `./actions.sh grid`).
Thank you!

**Comment by hotsezus** [comment]
@lukakemperle
I had the same problem until i figured out that Karabiner does not source my `~/.zshrc` and so there is no yabai binary in PATH.
In order to fix it you can use full path to the location where your yabai binary lives
<img width="849" alt="image" src="https://github.com/yqrashawn/GokuRakuJoudo/assets/39634495/74bfa60a-a3fa-428c-aa98-5b9e2f0ae425">

**Comment by lukakemperle** [comment]
> I had the same problem until i figured out that Karabiner does not source my `~/.zshrc` and so there is no yabai binary in PATH.

@hotsezus, thank you for the suggestion. -I currently use `yabai` in the template:

```
:templates {
:yabai "/usr/local/bin/yabai -m %s"
}
```

And the call it as `[:##semicolon [:yabai "display --focus east || yabai -m display --focus recent"]]`

Anyway, thank you & wish you a happy and productive 2024!

**Comment by yqrashawn** [comment]
you can also try set PATH like this https://github.com/yqrashawn/yqdotfiles/blob/863a771b8361c828a45eaa157d3d480c86dda9fd/modules/yqrashawn/home-manager/dotfiles/karabiner.edn#L55
