### ISSUE TITLE
Is there a way to change my json file to edn ? Thank you very much.

### ISSUE THREAD

**Issue by suliveevil** [yqrashawn/GokuRakuJoudo#24]
I have an about 2000 lines json file, how can I convert to edn format to manage my config?

**Comment by nikitavoloboev** [comment]
I don't think you can do it pragmatically. Unless someone builds a JSON to .edn converter but I don't think it's worth the hassle as you only will need to use it once and after have Goku do all the magic.

You should see what you are using and convert it to .edn step by step. Can reference docs or Telegram channel if you need help.

**Comment by suliveevil** [comment]
Agree with you. Thank you for your reply. ☺️
I should do it manually.
First day using Goku, want to simplify my config to have a better reading experience for others.
It seems this `main` in Goku is not one-to-one mapping to `manipulators` in karabiner.json.

![karabiner edn](https://user-images.githubusercontent.com/35763237/55575615-d89a6a80-5741-11e9-87f2-ef9048b3c98c.png)
![karabiner json](https://user-images.githubusercontent.com/35763237/55575618-dafcc480-5741-11e9-8d0d-491331dd1878.png)
