### ISSUE TITLE
Will Goku consider add specify file path feature？

### ISSUE THREAD

**Issue by suliveevil** [yqrashawn/GokuRakuJoudo#25]
I use [mackup](https://github.com/lra/mackup) to backup my settings of almost all my applications,  which means the `karabienr.edn` file path is `/allmyfiles/macOS-HOME/Mackup/.config/karabiner/karabienr.edn`.

Goku couldn't read from '/Users/$(whoami)/.config/karabiner.edn(symbolic link)'.

Here is the log:

```shell
Error: Path error: couldn't canonicalize '/Users/$(whoami)/.config/karabiner.edn':
Too many levels of symbolic links (os error 62)
```

So I move `karabiner.edn` back to `/Users/$(whoami)/.config/karabiner.edn`.

**Comment by nikitavoloboev** [comment]
You can move the file to wherever you want and create a symlink to the file from `.config`. That's what I do and it works for me.

**Comment by suliveevil** [comment]
The mackup use `ln -s` too, and Goku can't find the file through symbolic link.

```shell
Too many levels of symbolic links (os error 62)
```

I guess this problem may related to my `/allmyfiles/` folder, it is under root(same level to `/Users/`)

**Comment by yqrashawn** [comment]
@suliveevil I can't reproduce this error. I tried put karabiner.edn under `/` directory and `ln -s` it back to `~/.config/karabiner.edn`. Then give it the right permission with `chmod +rw /karabiner.edn`. 

Goku works fine.

Do your files have circular reference where a link is pointing back onto itself?

**Comment by suliveevil** [comment]
I listed all related information about this issue, no more to reference.
Now I gave up using mackup and manage my application setting manually.

**Comment by yqrashawn** [comment]
Added a environment variable `GOKU_EDN_CONFIG_FILE` to specify edn config file path in version 0.2.3.

**Comment by suliveevil** [comment]
Wow！Great feature！Thank you very much 😘
