### ISSUE TITLE
Map literal must contain an even number of forms Syntax Error

### ISSUE THREAD

**Issue by suliveevil** [yqrashawn/GokuRakuJoudo#26]
```shell
karabiner.edn:10:1: Read error: Map literal must contain an even number of forms Syntax Error
```

file content:

```ruby
{:profiles
 {:Goku {:sim 100
         :delay 500
         :alone 1000
         :held 500}}
 {:test {:sim     50
         :delay   500
         :alone   1000
         :held    500}}
}
```

Syntax error, but I can not find the Syntax error.

**Comment by suliveevil** [comment]
Learn Goku Syntax from karabiner.json using iThoughts in a clumsy way. 😂
<img width="885" alt="Goku" src="https://user-images.githubusercontent.com/35763237/55597829-19b26f00-5782-11e9-9279-a41005afdd07.png">

**Comment by lukakemperle** [comment]
> Learn Goku Syntax from karabiner.json using iThoughts in a clumsy way. 😂 

Have the save problem... -But unfortunately don't understand the problem with `Map literal`.

```
{:profiles
  {:Default { :default true
    :sim 50
    :delay 500
    :alone 1000
    :held 500
  }}
  {:Vim {
    :sim 60
    :delay 600
    :alone 2000
    :held 600}}

  :main [
    {:des "test"
      :rules [
        [:a :b]
      ]
    }
  ]
}
```
