### ISSUE TITLE
Adjust basic.simultaneous_threshold_milliseconds

### ISSUE THREAD

**Issue by cands** [yqrashawn/GokuRakuJoudo#29]
First, thank you for creating this fantastic tool for configuring Karabiner, it's immensely helpful! 

I have some problems with sometimes accidentally triggering some events while writing text, e.g. for the below rule I sometimes get an asterisk when writing words containing “sv”.
```
{:des “s-key (special characters)"
 :rules [:s-mode
            [:v :!Rbackslash] ; asterisk *
            ]}
```
I've tried to adjust the default timing parameters but it does not seem to help, currently using:
```
 {:Default {:default true
         :sim     50
         :delay   500
         :alone   1000
         :held    500}}
```
I'm not sure exactly how these delay parameters work and in what way to adjust them to avoid accidental triggering, since it seems somewhat poorly documented. I wonder if I would also need to adjust the 'basic.simultaneous_threshold_milliseconds' parameter. This seems to be static at 250 ms regardless of the default settings above. Can it be changed using Goku? 

I'm grateful for any advice how to solve the problem of accidentally triggering rules when typing ordinary text.

**Comment by yqrashawn** [comment]
Hi @cands , there's a global `:simlayer-threshold` [option](https://github.com/yqrashawn/yqdotfiles/blob/1e240bd89083ad8f4ef010aabc9b346a95d95af5/.config/karabiner.edn#L500) to config all simlayer's threshold.

We currently can't set profile specific threshold for simlayer and the [rule specific simlayer threshold setting](https://github.com/yqrashawn/GokuRakuJoudo/blob/c8c8c4d194a080c9bb0fdc8e3e2087b904a2abbe/src/karabiner_configurator/rules.clj#L199) doesn't work as suppose to. I'll fix it soon.

I think the global one will solve your problem, so I'll close this issue. Feel free to reopen it if that's not the case.

**Comment by cands** [comment]
Thank you very much for explaining, that global setting was just what I needed, after tuning the delay I get no accidental triggering of simlayers now!
