### ISSUE TITLE
[Question] Karabiner 12.4.0

### ISSUE THREAD

**Issue by lucaorio** [yqrashawn/GokuRakuJoudo#33]
Hello!

Is it safe to update to the latest version of Karabiner (`12.4.0`)?

I've seen a few things changing in the two previous minor releases, and I don't want to risk a sloppy update :D

Thanks!

**Comment by nikitavoloboev** [comment]
I’m on latest release and everything works fine for me. 

My configuration for reference: 

https://github.com/nikitavoloboev/dotfiles/blob/master/karabiner/karabiner.edn

**Comment by yqrashawn** [comment]
It's safe to update. 

If you are using hackintosh, the simlayer may not work well. It's not for sure. One of my two hackintosh machine has the problem. Maybe has somthing todo with the kext loading process. Can't figure it out.

**Comment by lucaorio** [comment]
@nikitavoloboev @yqrashawn Thanks a lot, I'm running on a regular Mac, so the regular update shouldn't cause any problem. 👍
