### ISSUE TITLE
Right side modifiers (QWER) don't work if used as mandatory and followed other optional modifiers 

### ISSUE THREAD

**Issue by QuestionDriven** [yqrashawn/GokuRakuJoudo#36]
When using the right side modifiers (QWER) as mandatory and with other optional modifiers, for example `:!Q#Rc`,  `goku` returns an error `ERROR: invalid special key keyword :!Q#Rc, no key :#Rc`

When using the left side modifiers (CTOS) in the same use case, such as `:!C#Rc`, it works.

The culprit seems the regex at [here](https://github.com/yqrashawn/GokuRakuJoudo/blob/master/src/karabiner_configurator/keys.clj#L33)
`(def special-modi-re #"(^![!CSTOFP]+#[#CSTOQWERFP]+)")`

**Comment by yqrashawn** [comment]
Thanks for your report. Fixed [here](https://github.com/yqrashawn/GokuRakuJoudo/commit/f22a61a76e3b73816b26830e0e07ee3b0b20ec70). 
You can use `brew update && brew upgrade goku` to update to version 0.2.6.
