### ISSUE TITLE
What is the status of WIP for different profile names?

### ISSUE THREAD

**Issue by gotjoshua** [yqrashawn/GokuRakuJoudo#39]
I see that the [profiles feature is still marked as WIP](https://github.com/yqrashawn/GokuRakuJoudo/blob/v0.2.6/examples.org#profiles-wip).

I was able to get it to work once with an alternate profile name, but then updates were silently failing. (Showing done! but not changing anything)

What is the status of this WIP?

**Comment by Holybasil** [comment]
The example doc for multiple profile is WIP. The feature is already implemented.
