### ISSUE TITLE
Support variables other than "1"

### ISSUE THREAD

**Issue by johnlindquist** [yqrashawn/GokuRakuJoudo#41]
I'd really like to check when

:multitouch_extension_finger_count

is set to "2", but I've spent hours reading the docs and examples and can't find a way.

My goal is to use 2 fingers on the trackpad as a shift key.

**Comment by yqrashawn** [comment]
Hi @johnlindquist 
Just write an example [here](https://github.com/yqrashawn/GokuRakuJoudo/blob/master/examples.org#use-the-multitouch-feature). You can specify the variable number other than 1 with the vector syntax.

Goku don't support specify "variable_unless" and a variable other than "1" with the simple syntax for now. 

I'll find time to add that feature.

**Comment by johnlindquist** [comment]
Thanks, much appreciated! Love this project

**Comment by lizyn** [comment]
Seems like simple syntax "variable_unless" is supported now? I tried prepending a ! to the variable name, and it just works (yes, I was just guessing), e.g. `:!variable_name`.

However, nowhere in this repo, including the example mentioned above covers that.
