### ISSUE TITLE
No :pipe key?

### ISSUE THREAD

**Issue by donnlee** [yqrashawn/GokuRakuJoudo#42]
I've got a rule that types out "foo bar" but I want it to type "foo | bar"
I cannot find a key definition like :pipe
Is there one?
I have found :spacebar :hyphen etc

**Comment by yqrashawn** [comment]
You can use [Karabiner-EventViewer.app](https://pqrs.org/osx/karabiner/document.html#eventviewer) to find out the keycode you want.

![image](https://user-images.githubusercontent.com/15090582/67447185-b0bf1580-f645-11e9-963e-ec8cfa7129f2.png)

The pipe sign is shift+backslash. It's `:Sbackslash` in goku.
There's also a [keys_info.clj](https://github.com/yqrashawn/GokuRakuJoudo/blob/master/src/karabiner_configurator/keys_info.clj) file where you can find all keys that goku support.

**Comment by donnlee** [comment]
facepalm. I should have known it's like typing on a real keyboard.  ty
