### ISSUE TITLE
Goku uses hardcoded paths to binaries

### ISSUE THREAD

**Issue by NicolaiSoeborg** [yqrashawn/GokuRakuJoudo#43]
E.g. https://github.com/yqrashawn/GokuRakuJoudo/blob/master/src/karabiner_configurator/core.clj#L31 I think it should instead use `$(brew --prefix <name>)` if brew is installed in a non-standard location.

**Comment by yqrashawn** [comment]
CI won't pass due to grallvm issue. Still not fixed.

**Comment by NicolaiSoeborg** [comment]
I moved my brew install, so its not a problem anymore in my system.
Maybe 5fd1d75 should just default to `/usr/local/` if `System/getenv "HOMEBREW_PREFIX"` fails?
