### ISSUE TITLE
can we make simple_modifications like complex_modifications in the karabiner.edn config file

### ISSUE THREAD

**Issue by materliu** [yqrashawn/GokuRakuJoudo#44]
In the karabiner.edu configure file, we declare rules, which will finally become complex_modifications. If I want to declare simple_modifications, can I get that by karabiner.edn ? I make the simple_modifications on the karabiner-elements GUI now.

**Comment by yqrashawn** [comment]
That's currently not supported. Goku only modifies the `profiles->complex_modifications` part in karabiner.json. You can always put simple modifications in the complex ones.

Goku can't set the `device` part and the `fn_function_keys` settings are usually vary by device.
