### ISSUE TITLE
Use modifier only in layer

### ISSUE THREAD

**Issue by babygau** [yqrashawn/GokuRakuJoudo#45]
Hi, is it possible to use a combination of modifier key only in layers without key code? 
```
{:layers {foobar {:modi [:left_shift : left_control]}}}
```

**Comment by yqrashawn** [comment]
That's not possible in a single layer. You need to define one layer say, for left_control another layer for left_shift pressed in left_control layer.

```clojure
 {:layers             {:lctrl-mode {:key :left_control}
                       :lshift-lctrl-mode {:key :left_shift :condi :lctrl-mode}
                       ......}

```
I don't recommend this, this will break all ctrl+/ctrl+shift+ keys and most keyboards have this build in already. You only need to remap those you don't like.

You can also define shortcuts for modifiers/tos/froms like [this](https://github.com/yqrashawn/yqdotfiles/blob/d944068c49796fe5a8e641bb33fea9d280cd35bf/.config/karabiner.edn#L14) and [this](https://github.com/yqrashawn/yqdotfiles/blob/d944068c49796fe5a8e641bb33fea9d280cd35bf/.config/karabiner.edn#L7).

Or you can come to the [telegram](https://t.me/karabinermac) group to see if other goku users have a better solution.

**Comment by babygau** [comment]
@yqrashawn many thanks 👍
