### ISSUE TITLE
Simlayers doesn't work on Hackintosh

### ISSUE THREAD

**Issue by onurguven** [yqrashawn/GokuRakuJoudo#51]
Simlayers doesn't work on Hackintosh.
I am using this keyboard [james donkey 612](https://www.amazon.com/James-Donkey-612-Mechanical-Keyboard/dp/B01N0J059M/
)

Karabiner Version: **12.9.2**
OS: MacOS Catalina **10.15.3**

No error message appears.

**Comment by yqrashawn** [comment]
Can you post your `karabiner.json` and `karabiner.edn` file here?

**Comment by narze** [comment]
I'm using hackintosh and it works fine, can you try it with real mac though?

**Comment by yqrashawn** [comment]
It works fine on my hackintosh and real mac.
