### ISSUE TITLE
type unicode characters

### ISSUE THREAD

**Issue by Hendekagon** [yqrashawn/GokuRakuJoudo#53]
Does Goku provide a way to configure a key sequence rule for typing unicode characters ? I couldn't find one in the examples. I want to a rule like `[[:right_shift :up_arrow] :↑]` to type ↑ when I do right-shift+up-arrow

**Comment by yqrashawn** [comment]
You can use the templates feature with applescript to do that. But it's a bit slow. See the example below.

https://github.com/yqrashawn/yqdotfiles/blob/f263b8f5129dca03ae92de59d2f936b0479c4fdc/.config/karabiner.edn#L23

I've tried to use shell command to call `pbcopy` and then type command+v. It won't work and I didn't look into it.
