### ISSUE TITLE
Missing `:des` (or typo) should yield error on Goku

### ISSUE THREAD

**Issue by narze** [yqrashawn/GokuRakuJoudo#56]
![image](https://user-images.githubusercontent.com/248741/76757986-4efd7480-67bb-11ea-8a1e-d1c03b2f8e9d.png)

When I purposely mistype (`:des` to `:Des` or `:de` or remove it) Goku still yields `Done!` but it should not since Karabiner logs raises error and confuse the user.

![image](https://user-images.githubusercontent.com/248741/76758169-c59a7200-67bb-11ea-8626-2c45f3a4ccac.png)

**Comment by yqrashawn** [comment]
fixed in v0.3.0
