### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by beautyfree** [yqrashawn/GokuRakuJoudo#59]
Looks like [example.edn](https://github.com/yqrashawn/GokuRakuJoudo/blob/master/resources/configurations/edn/example.edn) doesn't work:
```
❯ goku
Syntax error in config:
/Users/devall/.config/karabiner.edn:69:45: Read error: Map literal must contain an even number of forms
```

**Comment by yqrashawn** [comment]
fixed via 641b93cda6b56e0aa72c315457524f320f7ff77d
