### ISSUE TITLE
support for multiple profile

### ISSUE THREAD

**Issue by yqrashawn** [yqrashawn/GokuRakuJoudo#6]
let user specify a default profile name and profile for each manipulator.

**Comment by kchen0x** [comment]
How about making it work like original ways in KE. Goku generate the configs under assets directory, and user can choose which one the be enabled in their own profiles.

**Comment by yqrashawn** [comment]
The goal of goku is to enable user to write configs with ease and efficiency. User can config most things in goku without using Gui. There's no need to use the Gui to assign rules in goku to specific profile. 

As for configuration sharing, this might be feasible. But I think there's better way.

**Comment by kchen0x** [comment]
That's what i am facing, i'd like to share my config with my friends. So it's much more convenient to send them a url which can be easily imported with `karabiner://karabiner/assets/complex_modifications/import?url=<json_file>`. I wonder if you can provide some kind of export feature for json sharing.

**Comment by yqrashawn** [comment]
https://github.com/yqrashawn/GokuRakuJoudo/releases/tag/v0.2.0

**Comment by kchen0x** [comment]
This is definitely a cool release!

**Comment by yqrashawn** [comment]
Thanks! :D
