### ISSUE TITLE
Add 'shift' not left_shift or right_shift

### ISSUE THREAD

**Issue by waynehoover** [yqrashawn/GokuRakuJoudo#62]
Karabiner supports simply 'shift' which matches left and right shift, it would be nice to add that here:

https://github.com/yqrashawn/GokuRakuJoudo/blob/master/src/karabiner_configurator/keys.clj#L62

**Comment by yqrashawn** [comment]
Please check the changelog here https://github.com/yqrashawn/GokuRakuJoudo/blob/master/CHANGELOG.org#added

**Comment by aligndownpoured** [comment]
Thanks, this is very useful for my setup.
