### ISSUE TITLE
how to make a remapping conditional on current input source?

### ISSUE THREAD

**Issue by ndaniyar** [yqrashawn/GokuRakuJoudo#65]

**Comment by yqrashawn** [comment]
[Here](https://github.com/yqrashawn/yqdotfiles/blob/input-method-as-condition-example/.config/karabiner.edn#L62) is an example using input method as condition.
The `:abc` is defined [here](https://github.com/yqrashawn/yqdotfiles/blob/input-method-as-condition-example/.config/karabiner.edn#L622).

**Comment by ndaniyar** [comment]
Awesome, thanks!

How do I find this name `"^com\\.apple\\.keylayout\\.ABC$"`  for my input method?
I know that I can get a similar string for applications through event viewer, but not sure how to do it for input sources. Also, could you please clarify the difference between `input_source_id`, `input_mode_id` and `language`. I see that [here](https://github.com/yqrashawn/yqdotfiles/blob/340b7cbd4000ba6d4ba081c2d1ba7f4aa025ec92/.config/karabiner.edn#L11) you set all three, and 3 lines below you only set `input_source_id`.

Thanks!

**Comment by yqrashawn** [comment]
![image](https://user-images.githubusercontent.com/15090582/84098032-c2b8c180-aa38-11ea-9c5c-6b874a0ec825.png)
There's input_source in the `Variables` panel (check the second key in the image above). You can just specify `input_source_id` in your config under most circumstances. I guess the `input_mode_id` is for input methods that support more than 1 input mode and expose that to macos.
