### ISSUE TITLE
Question: is this possible?

### ISSUE THREAD

**Issue by alvaro-prieto** [yqrashawn/GokuRakuJoudo#69]
Hello, I've discovered Karabiner and Goku recently and now I'm in love with them. Is there any way to achieve this functionality?

caps_lock --> 'hyper'
h --> 'h'
hyper + tap h --> wait 300 ms. If no other 'h' tap happens during this interval, then: '('
hyper + double tap h (in less than 300ms) --> ')'

In this way, each key can have 3 options: normal value (single press), and 2 extra bindings in combination with hyper: single tap, and double tap.

h --> 'h'
hyper + h --> '('
hyper + tap h twice --> ')'

Is this possible? 

My plan is to bind all normal keys with a 'hyper' modifier (caps_lock) so that I can have all the symbols close to the resting position of my fingers. Since many of them come in pairs having double tap will help me a lot. 

So for example h will be --> '(' and ')', j will be --> '[' and ']', k will be --> '{' and '}' and so on. 

Thank you!

**Comment by alvaro-prieto** [comment]
I kind of achieved something similar in plain JSON, can anyone help me to translate it into Goku and maybe improve it? This is what I've got so far...   thank you!!!


```
{
  "description": "Press right_control once or twice",
  "manipulators": [
    {
      "type": "basic",
      "conditions": [
        {
          "name": "twice_flag",
          "type": "variable_if",
          "value": 0
        }
      ],
      "from": {
        "key_code": "right_control",
        "modifiers": {
          "optional": [
            "any"
          ]
        }
      },
      "to": [
        {
          "set_variable": {
            "name": "twice_flag",
            "value": 1
          }
        }
      ],
      "to_delayed_action": {
        "to_if_invoked": [
          {
            "key_code": "1"
          },
          {
            "set_variable": {
              "name": "twice_flag",
              "value": 0
            }
          }
        ],
        "to_if_canceled": []
      },
      "parameters": {
        "basic.to_delayed_action_delay_milliseconds": 300
      }
    },
    {
      "type": "basic",
      "conditions": [
        {
          "name": "twice_flag",
          "type": "variable_if",
          "value": 1
        }
      ],
      "from": {
        "key_code": "right_control",
        "modifiers": {
          "optional": [
            "any"
          ]
        }
      },
      "to": [
        {
          "key_code": "2"
        },
        {
          "set_variable": {
            "name": "twice_flag",
            "value": 0
          }
        }
      ]
    }
  ]
}
```

**Comment by yqrashawn** [comment]
Check the example at this commit https://github.com/yqrashawn/yqdotfiles/commit/4225edc6

The change at [line 62](https://github.com/yqrashawn/yqdotfiles/commit/4225edc6#diff-e0a7d8beeabf49db81aaf60277dcefa7R62) as a simlayer trigger by key `0`. You can think this as your hyper key.

There are two rules from [line 66](https://github.com/yqrashawn/yqdotfiles/commit/4225edc6#diff-e0a7d8beeabf49db81aaf60277dcefa7R66).

The first one mains 
- If variable `#69-a-level2` is 1 then press `a` insert `)`

The second one mains 
- If variable `#69-a-level2` is 0 then press `a` will set `#69-a-level2` to 1 and wait for 300ms. 
- And if 300ms past (`invoked`), insert `(` and set `#69-a-level2` to 0.
- And if it's interrupted by other keys (`canceled`), set `#69-a-level2` to 0.

**Comment by alvaro-prieto** [comment]
Thank you!! I will try it, you are very kind!! :-)

**Comment by alvaro-prieto** [comment]
It does work like charm! Thanks a lot. In my ISO-ES keyboard ( ) are located in !S8 and !S9, but that was easy to fix! Thanks a lot for this wonderful software and for your help!!

**Comment by yqrashawn** [comment]
Once your finish your config, you can create a PR to add your config [here](https://github.com/yqrashawn/GokuRakuJoudo/blob/master/in-the-wild.md) if you want.

**Comment by kaushikgopal** [comment]
@alvaro-prieto i know this is sometime back, but curious if you can post your answer here.

**Comment by alvaro-prieto** [comment]
@kaushikgopal  hello, it is been a while...  I don't even remember, I'm sorry, now I switched to QMK to have full freedom over my keyboard. I had a repo for my Karabiner / Goku stuff, maybe you can find something there: https://github.com/alvaro-prieto/splitLayout
