### ISSUE TITLE
Help with configuring a double-press key chord

### ISSUE THREAD

**Issue by yanneg** [yqrashawn/GokuRakuJoudo#70]
First, thanks for this awesome tool, it's certainly made my life easier for configuring Karabiner :)

What I'm trying to achieve is to double-press shift in order to switch into copy-mode inside iTerm.

I've taken some inspiration from https://github.com/yqrashawn/GokuRakuJoudo/issues/69 and I almost have it working:

```
{
    :des "iTerm2 S-S sequence to enter copy mode"
    :rules [
        :iterm2
        [:left_shift [:!CSc ["iterm2-copy-mode" 0]] ["iterm2-copy-mode" 1]]
        [:left_shift
            ["iterm2-copy-mode" 1]
            ["iterm2-copy-mode" 0]
            {:delayed {:invoked ["iterm2-copy-mode" 0] :canceled ["iterm2-copy-mode" 0]} :params {:delay 300}}
        ]
    ]
}
```

This works but I've lost the ability to use shift as a modifier. In other words, pressing shift-f prints "f" instead of "F" and shift-3 prints 3 instead of "#".

Is there any way to fix that?

**Comment by yqrashawn** [comment]
try this
```clojure
{:des "iTerm2 S-S sequence to enter copy mode"
 :rules [:iterm2
         [:left_shift [:!CSc ["iterm2-copy-mode" 0]] ["iterm2-copy-mode" 1]]
         [:left_shift
          [:left_shift ["iterm2-copy-mode" 1]]
          ["iterm2-copy-mode" 0]
          {:delayed {:invoked ["iterm2-copy-mode" 0] :canceled ["iterm2-copy-mode" 0]} :params {:delay 300}}]]}
```

**Comment by yanneg** [comment]
Thx for the assist @yqrashawn but that didn't work :(
The behaviour is still the same - double-tap shift to trigger `!CSc` works but holding it down and using it as a regular modifier doesn't.

**Comment by yqrashawn** [comment]
This should work. Invoke set varialbe first then `:left_shift`
```clojure
{:des "iTerm2 S-S sequence to enter copy mode"
              :rules [:Terminals
                      [:left_shift [:!CSc ["iterm2-copy-mode" 0]] ["iterm2-copy-mode" 1]]
                      [:left_shift
                       [["iterm2-copy-mode" 1] :left_shift]
                       ["iterm2-copy-mode" 0]
                       {:delayed {:invoked ["iterm2-copy-mode" 0] :canceled ["iterm2-copy-mode" 0]} :params {:delay 300}}]]}
```

**Comment by yanneg** [comment]
@yqrashawn worked like a champ! Thanks!
