### ISSUE TITLE
Functinality to open application; wait n seconds; submit key events

### ISSUE THREAD

**Issue by alexey-danilov** [yqrashawn/GokuRakuJoudo#75]
I want to replicate the setting, which I had in json karabiner config: open browser, wait 2 seconds, open new tab -> for quicker access to search.

So far I've come up with a configuration to open the browser:

{:des "hypr + e -> firefox" :rules [[:!!e "open '/Applications/Firefox.app'"]]}

It is possible to achieve the rest in goku?

**Comment by yqrashawn** [comment]
There's nothing wrong in this config. Although it's not work on my mac, it opens firefox and insert a t in the location bar. Does it have the same behavior on your side?

**Comment by MuhammedZakir** [comment]
> There's nothing wrong in this config. Although it's not work on my mac, it opens firefox and insert a t in the location bar. Does it have the same behavior on your side?

I am getting this now! IIRC, I didn't encounter this issue earlier because I didn't use hyper key. 

After fiddling with this, I found that
1. For some reason, using the same key in from and to_delayed_action is not working.
2. Key up event is not send for delayed action.t

This is what I came up with
```json
{
  "to_delayed_action": {
    "to_if_invoked": [
      {
        "key_code": "t",
        "modifiers": [
          "right_command"
        ]
      },
      {
        "key_code": "right_command"
      }
    ]
  },
  "parameters": {
    "basic.to_delayed_action_delay_milliseconds": 2000
  },
  "from": {
    "key_code": "e",
    "modifiers": {
      "mandatory": [
        "left_command",
        "left_control",
        "left_option",
        "left_shift"
      ]
    }
  },
  "to": [
    {
      "shell_command": "open '/Applications/Firefox.app'"
    }
  ],
  "type": "basic"
}
```

---

How can I write this in EDN? I modified delayed to `{:delayed {:invoked [:!Qt [:Q]]}`. But, I got `null` for second event instead of `right_command`. This maybe a bug in Goku because I got an error when I used modifier key as normal key in `to` event.

**Comment by MuhammedZakir** [comment]
>  **--snip--** 
>     1. For some reason, using the same key in from and to_delayed_action is not working.
>  **--snip--**

All mandatory modifiers in 'from' event are removed from 'to' events.

Ref: https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/from/modifiers/#frommodifiersmandatory

**Comment by yqrashawn** [comment]
@MuhammedZakir  `:invoked [:!Qt [:Q]]` need to be changed to `:invoked [:!Qt :right_command]`

**Comment by MuhammedZakir** [comment]
Thanks! It's working now! So you can only use abbreviations such as `Q` or `C`, in `from` events?

**Comment by yqrashawn** [comment]
> Thanks! It's working now! So you can only use abbreviations such as `Q` or `C`, in `from` events?

it can be used in `:main` section
