### ISSUE TITLE
provide goku setting to enable touch bar keyboard by default

### ISSUE THREAD

**Issue by kaushikgopal** [yqrashawn/GokuRakuJoudo#77]
The problem is that when you type modifiers along with some function keys, "Karabiner" doesn't read this well. 

Core Karabiner Issue: https://github.com/pqrs-org/Karabiner-Elements/issues/1700

If i manually apply the workaround suggested here https://github.com/pqrs-org/Karabiner-Elements/issues/535#issuecomment-350522019 , it "works" but the trouble is when i regenerate my karabiner.json from goku those settings are obviously wiped ☹️.

Is there a way in goku to basically enable the touch bar device by default?

**Comment by yqrashawn** [comment]
I believe the devices config in store in `devices` in each profile. goku only change the `complex_modifications` map https://github.com/yqrashawn/GokuRakuJoudo/blob/9fe23d5de54f14ff57bac80cf4d80e0c2ad733c7/src/karabiner_configurator/core.clj#L104

Are you sure it's caused by goku?

**Comment by kaushikgopal** [comment]
🤔 oh interesting. So here's the sequence of steps:

* i have goku compile to the json (everything works)
* i enable workaround from Karabiner-Elements devices preferences (my goku config works + everything else) but json changes (expected)
* i then run goku again (without changing anything else), the json changes (unexpected)

but you are right, it seems like it was just other parts of the config that probably changed. the workaround + goku customizations still continue to work.

I'll close this as this works as expected. I just didn't expect the json to change again.

Thanks for confirming!
