### ISSUE TITLE
How to bind keys that only have a numbered keycode (i.e. (number:207) or {"key_code":207}) ?

### ISSUE THREAD

**Issue by MrTastyBiscuits** [yqrashawn/GokuRakuJoudo#78]
First thing first, I am a newbie both with Github and Karabiner/Goku so please excuse any sloppiness in the wording of this issue…
I am trying to port my configuration from the json format to edn but I was not able to convert the following rule :
```
{
                        "description": "Remap PN to sleep",
                        "manipulators": [
                            {
                                "from": {
                                    "key_code": 207,
                                    "modifiers": {
                                        "optional": [
                                            "any"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "left_shift"
                                    }
                                ],
                                "to_if_alone": [
                                    {
                                        "key_code": "eject",
                                        "modifiers": [
                                            "left_command",
                                            "left_option"
                                        ]
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    }
```
This binds a key called Pn on my keyboard (a somewhat useless key used to program the keyboard itself that happens to output a key code to the computer) to put my Mac to sleep. 
My problem is that I am not able to define this Pn key with Goku. 
It's keycode is 207 (outputted this way by the EventViewer : (number:207) or {"key_code":207} ) but when try to assign it in Goku, it uses it's quoted form in the generated json, which does not work :
```
…
"from" : { "key_code" : "207" },                            ;; should be "key_code" : 207 as above
…
```
I have searched the docs but have not been able to find a solution. How do we do that in Goku ?
Thanks !

**Comment by babygau** [comment]
could you post your goku config?

**Comment by MrTastyBiscuits** [comment]
I got the closest to my goal by using the following: 

• This "from" definition:
`:froms {:pnbutton {:key :207}}`

• Together with this remapping (in main):
```
{:des "Remap Pn to sleep"
         :rules [
          [:pnbutton :left_shift :vortex {:alone :!COeject}
                ]}
```
It generated pretty much the same config as my current json with the exception of the quotes around the 207, that I mentioned above.


For reference, here is the event seen by Karabiner-EventViewer when the key is pressed:
```
type:key_down        code:207        name:(number:207)    misc:
type:key_up          code:207        name:(number:207)    misc:
```

**Comment by babygau** [comment]
as far as i know, goku doesn't accept key which is not defined in its  [list](https://www.github.com/yqrashawn/GokuRakuJoudo/tree/master/src%2Fkarabiner_configurator%2Fkeys_info.clj)

however there is a workaround you could try by using simple modification.

go to simple modification tab, change your hardcoded key to `left_shift`, then in goku config, do

```
​{:des "Remap Pn to sleep"
         :rules [
          [:##left_shift :left_shift :vortex {:alone :!COeject}]}
```

**Comment by MrTastyBiscuits** [comment]
Hahaha tunnel vision cranked up to 11, I should have thought about the "simple modifications". Your trick works perfectly. I am surprised that goku does not support that directly but the simple modification fits well in my "bodging" approach.

It would be great if goku had an option to support raw key codes (but admittedly less readable than a list of predefined keys), especially in cases like this one with a keyboard that has a weird macro(-ish) key.

Thank you for your time and help!

**Comment by babygau** [comment]
you're welcome. if your problem is solved, you can close it 😎

**Comment by yqrashawn** [comment]
May I ask what this key show in the simple modification dropdown? Is it 207? There's a key definition file in goku [here](https://github.com/yqrashawn/GokuRakuJoudo/blob/0046266e8dccda65c7a2213c7b4b8a02a3d713a6/src/karabiner_configurator/keys_info.clj#L3) which don't contain `207`. Does karabiner dynamically detect keys on hardware?

**Comment by MrTastyBiscuits** [comment]
From my amateur point of view, **no, it does not seem that Karabiner detects keys dynamically.** 

By default the key does not appear in the "simple modifications" dropdown.
Then, if I use the EventViewer and press on this "Pn" key, I get the output mentioned in my penultimate message along with the option to "Add \`(number:207)\`to Karabiner-Elements".

It is only when this button is clicked that Karabiner creates a new simple modification line with this as the **"from key: `{"key_code":207}`**. It lives at the very bottom of the dropdown.

Note that Karabiner does not "remember" the existence of this key ; if I delete the simple modification, it will not appear in the dropdown anymore. I will have to go through the above-mentioned steps again to map it.

**Comment by yqrashawn** [comment]
Ok. So it works if you specify the rule in the complex modification section in karabiner.json file right?

**Comment by MrTastyBiscuits** [comment]
Yes, that is right.
If I want to use Goku, I have to use the simple modifications in the GUI to remap the key first and then use Goku to create the complex modification on the reassigned key.
If I do it directly in karabiner.json, I can skip the simple modification and just enter the snippet of code in my first message (that has the 207 without quotes).
