### ISSUE TITLE
how to set custom variable when open a file type?

### ISSUE THREAD

**Issue by babygau** [yqrashawn/GokuRakuJoudo#79]
@yqrashawn, in the example section
[same key in different mode](https://github.com/yqrashawn/GokuRakuJoudo/blob/master/examples.org#same-key-in-different-mode-from-nikitavoloboevs-config), you say that we can set _custom variable_ when open a file type using _karabiner cli_, but i'm wondering how we can do that? could you elaborate?

**Comment by yqrashawn** [comment]
Seems the link is broken in the doc. I never tried it on my own. But [karabiner's cli](https://karabiner-elements.pqrs.org/docs/manual/misc/command-line-interface/) has the arg `--set-variables` which can 
> Set variables which are used in complex modifications.

So I suppose user can, for example, set the `editing_file_cpp` variable by invoking some editor functionality to execute shell script when opening a `.cpp` file. Combine with a current application condition user can define rules for editing cpp file in each application.

**Comment by babygau** [comment]
> So I suppose user can, for example, set the editing_file_cpp variable by invoking some editor functionality to execute shell script when opening a .cpp file

thank you, that's what i thought. i think whenever a project is opened, we can run a simple task that execute `karabiner_cli` to set the variable.
