### ISSUE TITLE
how to use unused key f19?

### ISSUE THREAD

**Issue by babygau** [yqrashawn/GokuRakuJoudo#82]
in my case, i want to remap `ctrl` to `f19`

```
:layers {:foo-mode {:key :f19}}
{:rules [
    [:right_ctrl :f19]
    [:f19 :!TO]
]}
```
however `foo-mode` return `0` when i press and hold `ctrl`.

**Comment by yqrashawn** [comment]
I think you need to map right control to f19 in simple modification and then use f19 as right control in complex modification.

**Comment by babygau** [comment]
> I think you need to map right control to f19 in simple modification and then use f19 as right control in complex modification.

i tried but `foo-mode` variable is `0` when i hold `ctrl` key

**Comment by yqrashawn** [comment]
Is this still a question to you?

Basically, you can't map a key to be both layer trigger key and modifier key when pressed with another key.

**Comment by babygau** [comment]
It's no longer my issue, I tried other solution for my remap workflow.
