### ISSUE TITLE
[Proposal] Use currently selected profile instead of 'Default'

### ISSUE THREAD

**Issue by MuhammedZakir** [yqrashawn/GokuRakuJoudo#83]
Profile name is at `.profiles[x].name` and selection indicator is at `.profiles[x].selected` - `true` if selected, else `false`.

So Goku should use the profile whose `selected` is `true`.  Also, is it possible to append generated rules to existing ones rather than replacing them?

**Comment by yqrashawn** [comment]
goku supports specify profile name, with the following example, goku will only change the profile named "Goku".

```clojure
{:profiles
 {:Goku {:default true :sim 50 :delay 500 :alone 500 :held 500}}
 :tos ...
 :modifiers ...
 :templates ...
 :main ...}
```

**Comment by MuhammedZakir** [comment]
Thanks! But what I was asking was, if no `:profiles` is specified in Goku config file, then use the currently selected profile instead of "Default", which is what Goku currently use.

> Also, is it possible to append generated rules to existing ones rather than replacing them?

Can this be implemented? This is helpful when converting existing JSON config. If you have a large config, it will take some time to write it in EDN, especially for someone not familiar with the syntax. SO with this, we can convert JSON to EDN gradually.
