### ISSUE TITLE
mouse rule doesn't work, please help

### ISSUE THREAD

**Issue by MagnificentSteiner** [yqrashawn/GokuRakuJoudo#84]
I'm trying to set on my mouse the function: any key + button4 -> any key + left_arrow (for example, left_command + button4 -> left_command + left_arrow) but I get this error "ERROR: invalid special key keyword :##, no key :Failed!"
Here is the incorrect code:

{:des "Tecknet Wireless Mouse keys mapping"
        :rules [:twm
        [:##{:pkey :button4} :left_arrow] 
        [:##{:pkey :button5} :right_arrow] 
        ]}

I need your help!

**Comment by MagnificentSteiner** [comment]
Is there a way to use !/!!/#/## with pointing buttons (mouse) like {:pkey ...}?

**Comment by babygau** [comment]
@MagnificentSteiner just use `:##button4`. you had wrong syntax

**Comment by MagnificentSteiner** [comment]
@babygau Thank you very much, of course now it works ;)

**Comment by MagnificentSteiner** [comment]
@babygau No, actually it doesn't work, the correct syntax for mice buttons is, for instance, {:pkey :button4}. 
Just :button4 (or :##button4) is not recognized.

**Comment by babygau** [comment]
Unfortunately, I don't find `:pkey` in [goku key info](https://github.com/yqrashawn/GokuRakuJoudo/blob/master/src/karabiner_configurator/keys_info.clj)

**Comment by MagnificentSteiner** [comment]
@babygau Yes, they didn't specified the {:pkey :buttonx} syntax there. Though, you can verify that in almost every dotfile shared as examples in "Goku in the wild" section there is this syntax {:pkey :buttonx}. 
See for example, [https://github.com/yqrashawn/yqdotfiles/blob/master/.config/karabiner.edn]()

**Comment by babygau** [comment]
hmm, interesting, i missed that. 

how about `{:pkey :button4 :modi :any}`

**Comment by MagnificentSteiner** [comment]
@babygau Thank you very much, now both ways work fine.

**Comment by yqrashawn** [comment]
Really thanks for your help @babygau   

Can this be closed? @MagnificentSteiner
