### ISSUE TITLE
Replace "\"key with "ñ" key

### ISSUE THREAD

**Issue by VeniceNerd** [yqrashawn/GokuRakuJoudo#85]
Hey guys,

I'm having a really hard time using Karabiner to replace my "\" key with the "ñ" key. The simple key replacement doesn't seem to work for me because the "ñ" key doesn't show up in my replacement options. Only my English keyboard keys show up.

Any help with this would be so greatly appreciated!

**Comment by yqrashawn** [comment]
What's the key showing in event viewer when you press it?

**Comment by dannylittle715** [comment]
This works for me:
```
{:des "backslash to ñ" :rules [[:backslash [:!On :n]]]}
```
the 'to' is just hitting option-n, and then 'n'.

**Comment by yqrashawn** [comment]
Thanks for your help @dannylittle715
Feel free to reopen @VeniceNerd
