### ISSUE TITLE
Identify application from file path?

### ISSUE THREAD

**Issue by remy** [yqrashawn/GokuRakuJoudo#98]
I've got a program (mono on the mac) that doesn't have a bundle identifier, but does have a path. I know that Karabiner can identify using `file_path` but I can't see how I would do that using GokuRakuJoudo.

I've tried dropping the path in the same manner as the bundler identifier (as a test) but this doesn't seem to work either:

```
  :applications {
    :vscode [ "^com\\.microsoft\\.VSCode$"]		; works
    :mono ["^\\/usr\\/local\\/bin\\/mono$"]		; doesn't, but not sure how to target
  }
```

Any advice? Thanks in advance.

**Comment by yqrashawn** [comment]
This feature is added in 0.3.4. There's example in the changelog https://github.com/yqrashawn/GokuRakuJoudo/blob/master/CHANGELOG.org#034---2020-12-25.

You can use `brew upgrade goku` to upgrade to latest version.
